/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_problem_cost_ext_cost_hess_xu_p_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {461, 1, 1};
static const casadi_int casadi_s4[577] = 
  {14, 196, 0, 1, 3, 5, 7, 9,
  11, 13, 15, 17, 19, 21, 23, 25,
  27, 29, 30, 32, 34, 36, 38, 40,
  42, 44, 46, 48, 50, 52, 54, 56,
  58, 59, 61, 63, 65, 67, 69, 71,
  73, 75, 77, 79, 81, 83, 85, 87,
  88, 90, 92, 94, 96, 98, 100, 102,
  104, 106, 108, 110, 112, 114, 116, 117,
  119, 121, 123, 125, 127, 129, 131, 133,
  135, 137, 139, 141, 143, 145, 146, 148,
  150, 152, 154, 156, 158, 160, 162, 164,
  166, 168, 170, 172, 174, 175, 177, 179,
  181, 183, 185, 187, 189, 191, 193, 195,
  197, 199, 201, 203, 204, 206, 208, 210,
  212, 214, 216, 218, 220, 222, 224, 226,
  228, 230, 232, 233, 235, 237, 239, 241,
  243, 245, 247, 249, 251, 253, 255, 257,
  259, 261, 262, 264, 266, 268, 270, 272,
  274, 276, 278, 280, 282, 284, 286, 288,
  290, 291, 293, 295, 297, 299, 301, 303,
  305, 307, 309, 311, 313, 315, 317, 319,
  320, 322, 324, 326, 328, 330, 332, 334,
  336, 338, 340, 342, 344, 346, 348, 349,
  351, 353, 355, 357, 359, 361, 363, 365,
  367, 369, 371, 373, 375, 377, 378, 4,
  4, 5, 4, 6, 4, 7, 4, 8,
  4, 9, 4, 10, 4, 11, 4, 12,
  4, 13, 0, 4, 1, 4, 2, 4,
  3, 4, 4, 5, 5, 5, 6, 5,
  7, 5, 8, 5, 9, 5, 10, 5,
  11, 5, 12, 5, 13, 0, 5, 1,
  5, 2, 5, 3, 5, 4, 6, 5,
  6, 6, 6, 7, 6, 8, 6, 9,
  6, 10, 6, 11, 6, 12, 6, 13,
  0, 6, 1, 6, 2, 6, 3, 6,
  4, 7, 5, 7, 6, 7, 7, 7,
  8, 7, 9, 7, 10, 7, 11, 7,
  12, 7, 13, 0, 7, 1, 7, 2,
  7, 3, 7, 4, 8, 5, 8, 6,
  8, 7, 8, 8, 8, 9, 8, 10,
  8, 11, 8, 12, 8, 13, 0, 8,
  1, 8, 2, 8, 3, 8, 4, 9,
  5, 9, 6, 9, 7, 9, 8, 9,
  9, 9, 10, 9, 11, 9, 12, 9,
  13, 0, 9, 1, 9, 2, 9, 3,
  9, 4, 10, 5, 10, 6, 10, 7,
  10, 8, 10, 9, 10, 10, 10, 11,
  10, 12, 10, 13, 0, 10, 1, 10,
  2, 10, 3, 10, 4, 11, 5, 11,
  6, 11, 7, 11, 8, 11, 9, 11,
  10, 11, 11, 11, 12, 11, 13, 0,
  11, 1, 11, 2, 11, 3, 11, 4,
  12, 5, 12, 6, 12, 7, 12, 8,
  12, 9, 12, 10, 12, 11, 12, 12,
  12, 13, 0, 12, 1, 12, 2, 12,
  3, 12, 4, 13, 5, 13, 6, 13,
  7, 13, 8, 13, 9, 13, 10, 13,
  11, 13, 12, 13, 13, 0, 13, 1,
  13, 2, 13, 3, 13, 0, 4, 0,
  5, 0, 6, 0, 7, 0, 8, 0,
  9, 0, 10, 0, 11, 0, 12, 0,
  13, 0, 0, 1, 0, 2, 0, 3,
  1, 4, 1, 5, 1, 6, 1, 7,
  1, 8, 1, 9, 1, 10, 1, 11,
  1, 12, 1, 13, 0, 1, 1, 1,
  2, 1, 3, 2, 4, 2, 5, 2,
  6, 2, 7, 2, 8, 2, 9, 2,
  10, 2, 11, 2, 12, 2, 13, 0,
  2, 1, 2, 2, 2, 3, 3, 4,
  3, 5, 3, 6, 3, 7, 3, 8,
  3, 9, 3, 10, 3, 11, 3, 12,
  3, 13, 0, 3, 1, 3, 2, 3,
  3};

/* ocp_problem_cost_ext_cost_hess_xu_p:(i0[10],i1[4],i2[0],i3[0],i4[461])->(o0[14x196,378nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14;
  a00=arg[0]? arg[0][0] : 0;
  a01=(a00+a00);
  if (res[0]!=0) res[0][0]=a01;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  if (res[0]!=0) res[0][2]=a00;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][3]=a02;
  if (res[0]!=0) res[0][4]=a00;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][5]=a03;
  if (res[0]!=0) res[0][6]=a00;
  a04=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][7]=a04;
  if (res[0]!=0) res[0][8]=a00;
  a05=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][9]=a05;
  if (res[0]!=0) res[0][10]=a00;
  a06=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][11]=a06;
  if (res[0]!=0) res[0][12]=a00;
  a07=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][13]=a07;
  if (res[0]!=0) res[0][14]=a00;
  a08=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][15]=a08;
  if (res[0]!=0) res[0][16]=a00;
  a09=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][17]=a09;
  if (res[0]!=0) res[0][18]=a00;
  if (res[0]!=0) res[0][19]=a00;
  a10=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][20]=a10;
  if (res[0]!=0) res[0][21]=a00;
  a11=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][22]=a11;
  if (res[0]!=0) res[0][23]=a00;
  a12=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][24]=a12;
  if (res[0]!=0) res[0][25]=a00;
  a13=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][26]=a13;
  if (res[0]!=0) res[0][27]=a01;
  if (res[0]!=0) res[0][28]=a00;
  a14=(a01+a01);
  if (res[0]!=0) res[0][29]=a14;
  if (res[0]!=0) res[0][30]=a02;
  if (res[0]!=0) res[0][31]=a01;
  if (res[0]!=0) res[0][32]=a03;
  if (res[0]!=0) res[0][33]=a01;
  if (res[0]!=0) res[0][34]=a04;
  if (res[0]!=0) res[0][35]=a01;
  if (res[0]!=0) res[0][36]=a05;
  if (res[0]!=0) res[0][37]=a01;
  if (res[0]!=0) res[0][38]=a06;
  if (res[0]!=0) res[0][39]=a01;
  if (res[0]!=0) res[0][40]=a07;
  if (res[0]!=0) res[0][41]=a01;
  if (res[0]!=0) res[0][42]=a08;
  if (res[0]!=0) res[0][43]=a01;
  if (res[0]!=0) res[0][44]=a09;
  if (res[0]!=0) res[0][45]=a01;
  if (res[0]!=0) res[0][46]=a01;
  if (res[0]!=0) res[0][47]=a10;
  if (res[0]!=0) res[0][48]=a01;
  if (res[0]!=0) res[0][49]=a11;
  if (res[0]!=0) res[0][50]=a01;
  if (res[0]!=0) res[0][51]=a12;
  if (res[0]!=0) res[0][52]=a01;
  if (res[0]!=0) res[0][53]=a13;
  if (res[0]!=0) res[0][54]=a02;
  if (res[0]!=0) res[0][55]=a00;
  if (res[0]!=0) res[0][56]=a02;
  if (res[0]!=0) res[0][57]=a01;
  a14=(a02+a02);
  if (res[0]!=0) res[0][58]=a14;
  if (res[0]!=0) res[0][59]=a03;
  if (res[0]!=0) res[0][60]=a02;
  if (res[0]!=0) res[0][61]=a04;
  if (res[0]!=0) res[0][62]=a02;
  if (res[0]!=0) res[0][63]=a05;
  if (res[0]!=0) res[0][64]=a02;
  if (res[0]!=0) res[0][65]=a06;
  if (res[0]!=0) res[0][66]=a02;
  if (res[0]!=0) res[0][67]=a07;
  if (res[0]!=0) res[0][68]=a02;
  if (res[0]!=0) res[0][69]=a08;
  if (res[0]!=0) res[0][70]=a02;
  if (res[0]!=0) res[0][71]=a09;
  if (res[0]!=0) res[0][72]=a02;
  if (res[0]!=0) res[0][73]=a02;
  if (res[0]!=0) res[0][74]=a10;
  if (res[0]!=0) res[0][75]=a02;
  if (res[0]!=0) res[0][76]=a11;
  if (res[0]!=0) res[0][77]=a02;
  if (res[0]!=0) res[0][78]=a12;
  if (res[0]!=0) res[0][79]=a02;
  if (res[0]!=0) res[0][80]=a13;
  if (res[0]!=0) res[0][81]=a03;
  if (res[0]!=0) res[0][82]=a00;
  if (res[0]!=0) res[0][83]=a03;
  if (res[0]!=0) res[0][84]=a01;
  if (res[0]!=0) res[0][85]=a03;
  if (res[0]!=0) res[0][86]=a02;
  a14=(a03+a03);
  if (res[0]!=0) res[0][87]=a14;
  if (res[0]!=0) res[0][88]=a04;
  if (res[0]!=0) res[0][89]=a03;
  if (res[0]!=0) res[0][90]=a05;
  if (res[0]!=0) res[0][91]=a03;
  if (res[0]!=0) res[0][92]=a06;
  if (res[0]!=0) res[0][93]=a03;
  if (res[0]!=0) res[0][94]=a07;
  if (res[0]!=0) res[0][95]=a03;
  if (res[0]!=0) res[0][96]=a08;
  if (res[0]!=0) res[0][97]=a03;
  if (res[0]!=0) res[0][98]=a09;
  if (res[0]!=0) res[0][99]=a03;
  if (res[0]!=0) res[0][100]=a03;
  if (res[0]!=0) res[0][101]=a10;
  if (res[0]!=0) res[0][102]=a03;
  if (res[0]!=0) res[0][103]=a11;
  if (res[0]!=0) res[0][104]=a03;
  if (res[0]!=0) res[0][105]=a12;
  if (res[0]!=0) res[0][106]=a03;
  if (res[0]!=0) res[0][107]=a13;
  if (res[0]!=0) res[0][108]=a04;
  if (res[0]!=0) res[0][109]=a00;
  if (res[0]!=0) res[0][110]=a04;
  if (res[0]!=0) res[0][111]=a01;
  if (res[0]!=0) res[0][112]=a04;
  if (res[0]!=0) res[0][113]=a02;
  if (res[0]!=0) res[0][114]=a04;
  if (res[0]!=0) res[0][115]=a03;
  a14=(a04+a04);
  if (res[0]!=0) res[0][116]=a14;
  if (res[0]!=0) res[0][117]=a05;
  if (res[0]!=0) res[0][118]=a04;
  if (res[0]!=0) res[0][119]=a06;
  if (res[0]!=0) res[0][120]=a04;
  if (res[0]!=0) res[0][121]=a07;
  if (res[0]!=0) res[0][122]=a04;
  if (res[0]!=0) res[0][123]=a08;
  if (res[0]!=0) res[0][124]=a04;
  if (res[0]!=0) res[0][125]=a09;
  if (res[0]!=0) res[0][126]=a04;
  if (res[0]!=0) res[0][127]=a04;
  if (res[0]!=0) res[0][128]=a10;
  if (res[0]!=0) res[0][129]=a04;
  if (res[0]!=0) res[0][130]=a11;
  if (res[0]!=0) res[0][131]=a04;
  if (res[0]!=0) res[0][132]=a12;
  if (res[0]!=0) res[0][133]=a04;
  if (res[0]!=0) res[0][134]=a13;
  if (res[0]!=0) res[0][135]=a05;
  if (res[0]!=0) res[0][136]=a00;
  if (res[0]!=0) res[0][137]=a05;
  if (res[0]!=0) res[0][138]=a01;
  if (res[0]!=0) res[0][139]=a05;
  if (res[0]!=0) res[0][140]=a02;
  if (res[0]!=0) res[0][141]=a05;
  if (res[0]!=0) res[0][142]=a03;
  if (res[0]!=0) res[0][143]=a05;
  if (res[0]!=0) res[0][144]=a04;
  a14=(a05+a05);
  if (res[0]!=0) res[0][145]=a14;
  if (res[0]!=0) res[0][146]=a06;
  if (res[0]!=0) res[0][147]=a05;
  if (res[0]!=0) res[0][148]=a07;
  if (res[0]!=0) res[0][149]=a05;
  if (res[0]!=0) res[0][150]=a08;
  if (res[0]!=0) res[0][151]=a05;
  if (res[0]!=0) res[0][152]=a09;
  if (res[0]!=0) res[0][153]=a05;
  if (res[0]!=0) res[0][154]=a05;
  if (res[0]!=0) res[0][155]=a10;
  if (res[0]!=0) res[0][156]=a05;
  if (res[0]!=0) res[0][157]=a11;
  if (res[0]!=0) res[0][158]=a05;
  if (res[0]!=0) res[0][159]=a12;
  if (res[0]!=0) res[0][160]=a05;
  if (res[0]!=0) res[0][161]=a13;
  if (res[0]!=0) res[0][162]=a06;
  if (res[0]!=0) res[0][163]=a00;
  if (res[0]!=0) res[0][164]=a06;
  if (res[0]!=0) res[0][165]=a01;
  if (res[0]!=0) res[0][166]=a06;
  if (res[0]!=0) res[0][167]=a02;
  if (res[0]!=0) res[0][168]=a06;
  if (res[0]!=0) res[0][169]=a03;
  if (res[0]!=0) res[0][170]=a06;
  if (res[0]!=0) res[0][171]=a04;
  if (res[0]!=0) res[0][172]=a06;
  if (res[0]!=0) res[0][173]=a05;
  a14=(a06+a06);
  if (res[0]!=0) res[0][174]=a14;
  if (res[0]!=0) res[0][175]=a07;
  if (res[0]!=0) res[0][176]=a06;
  if (res[0]!=0) res[0][177]=a08;
  if (res[0]!=0) res[0][178]=a06;
  if (res[0]!=0) res[0][179]=a09;
  if (res[0]!=0) res[0][180]=a06;
  if (res[0]!=0) res[0][181]=a06;
  if (res[0]!=0) res[0][182]=a10;
  if (res[0]!=0) res[0][183]=a06;
  if (res[0]!=0) res[0][184]=a11;
  if (res[0]!=0) res[0][185]=a06;
  if (res[0]!=0) res[0][186]=a12;
  if (res[0]!=0) res[0][187]=a06;
  if (res[0]!=0) res[0][188]=a13;
  if (res[0]!=0) res[0][189]=a07;
  if (res[0]!=0) res[0][190]=a00;
  if (res[0]!=0) res[0][191]=a07;
  if (res[0]!=0) res[0][192]=a01;
  if (res[0]!=0) res[0][193]=a07;
  if (res[0]!=0) res[0][194]=a02;
  if (res[0]!=0) res[0][195]=a07;
  if (res[0]!=0) res[0][196]=a03;
  if (res[0]!=0) res[0][197]=a07;
  if (res[0]!=0) res[0][198]=a04;
  if (res[0]!=0) res[0][199]=a07;
  if (res[0]!=0) res[0][200]=a05;
  if (res[0]!=0) res[0][201]=a07;
  if (res[0]!=0) res[0][202]=a06;
  a14=(a07+a07);
  if (res[0]!=0) res[0][203]=a14;
  if (res[0]!=0) res[0][204]=a08;
  if (res[0]!=0) res[0][205]=a07;
  if (res[0]!=0) res[0][206]=a09;
  if (res[0]!=0) res[0][207]=a07;
  if (res[0]!=0) res[0][208]=a07;
  if (res[0]!=0) res[0][209]=a10;
  if (res[0]!=0) res[0][210]=a07;
  if (res[0]!=0) res[0][211]=a11;
  if (res[0]!=0) res[0][212]=a07;
  if (res[0]!=0) res[0][213]=a12;
  if (res[0]!=0) res[0][214]=a07;
  if (res[0]!=0) res[0][215]=a13;
  if (res[0]!=0) res[0][216]=a08;
  if (res[0]!=0) res[0][217]=a00;
  if (res[0]!=0) res[0][218]=a08;
  if (res[0]!=0) res[0][219]=a01;
  if (res[0]!=0) res[0][220]=a08;
  if (res[0]!=0) res[0][221]=a02;
  if (res[0]!=0) res[0][222]=a08;
  if (res[0]!=0) res[0][223]=a03;
  if (res[0]!=0) res[0][224]=a08;
  if (res[0]!=0) res[0][225]=a04;
  if (res[0]!=0) res[0][226]=a08;
  if (res[0]!=0) res[0][227]=a05;
  if (res[0]!=0) res[0][228]=a08;
  if (res[0]!=0) res[0][229]=a06;
  if (res[0]!=0) res[0][230]=a08;
  if (res[0]!=0) res[0][231]=a07;
  a14=(a08+a08);
  if (res[0]!=0) res[0][232]=a14;
  if (res[0]!=0) res[0][233]=a09;
  if (res[0]!=0) res[0][234]=a08;
  if (res[0]!=0) res[0][235]=a08;
  if (res[0]!=0) res[0][236]=a10;
  if (res[0]!=0) res[0][237]=a08;
  if (res[0]!=0) res[0][238]=a11;
  if (res[0]!=0) res[0][239]=a08;
  if (res[0]!=0) res[0][240]=a12;
  if (res[0]!=0) res[0][241]=a08;
  if (res[0]!=0) res[0][242]=a13;
  if (res[0]!=0) res[0][243]=a09;
  if (res[0]!=0) res[0][244]=a00;
  if (res[0]!=0) res[0][245]=a09;
  if (res[0]!=0) res[0][246]=a01;
  if (res[0]!=0) res[0][247]=a09;
  if (res[0]!=0) res[0][248]=a02;
  if (res[0]!=0) res[0][249]=a09;
  if (res[0]!=0) res[0][250]=a03;
  if (res[0]!=0) res[0][251]=a09;
  if (res[0]!=0) res[0][252]=a04;
  if (res[0]!=0) res[0][253]=a09;
  if (res[0]!=0) res[0][254]=a05;
  if (res[0]!=0) res[0][255]=a09;
  if (res[0]!=0) res[0][256]=a06;
  if (res[0]!=0) res[0][257]=a09;
  if (res[0]!=0) res[0][258]=a07;
  if (res[0]!=0) res[0][259]=a09;
  if (res[0]!=0) res[0][260]=a08;
  a14=(a09+a09);
  if (res[0]!=0) res[0][261]=a14;
  if (res[0]!=0) res[0][262]=a09;
  if (res[0]!=0) res[0][263]=a10;
  if (res[0]!=0) res[0][264]=a09;
  if (res[0]!=0) res[0][265]=a11;
  if (res[0]!=0) res[0][266]=a09;
  if (res[0]!=0) res[0][267]=a12;
  if (res[0]!=0) res[0][268]=a09;
  if (res[0]!=0) res[0][269]=a13;
  if (res[0]!=0) res[0][270]=a00;
  if (res[0]!=0) res[0][271]=a10;
  if (res[0]!=0) res[0][272]=a01;
  if (res[0]!=0) res[0][273]=a10;
  if (res[0]!=0) res[0][274]=a02;
  if (res[0]!=0) res[0][275]=a10;
  if (res[0]!=0) res[0][276]=a03;
  if (res[0]!=0) res[0][277]=a10;
  if (res[0]!=0) res[0][278]=a04;
  if (res[0]!=0) res[0][279]=a10;
  if (res[0]!=0) res[0][280]=a05;
  if (res[0]!=0) res[0][281]=a10;
  if (res[0]!=0) res[0][282]=a06;
  if (res[0]!=0) res[0][283]=a10;
  if (res[0]!=0) res[0][284]=a07;
  if (res[0]!=0) res[0][285]=a10;
  if (res[0]!=0) res[0][286]=a08;
  if (res[0]!=0) res[0][287]=a10;
  if (res[0]!=0) res[0][288]=a09;
  if (res[0]!=0) res[0][289]=a10;
  a14=(a10+a10);
  if (res[0]!=0) res[0][290]=a14;
  if (res[0]!=0) res[0][291]=a11;
  if (res[0]!=0) res[0][292]=a10;
  if (res[0]!=0) res[0][293]=a12;
  if (res[0]!=0) res[0][294]=a10;
  if (res[0]!=0) res[0][295]=a13;
  if (res[0]!=0) res[0][296]=a10;
  if (res[0]!=0) res[0][297]=a00;
  if (res[0]!=0) res[0][298]=a11;
  if (res[0]!=0) res[0][299]=a01;
  if (res[0]!=0) res[0][300]=a11;
  if (res[0]!=0) res[0][301]=a02;
  if (res[0]!=0) res[0][302]=a11;
  if (res[0]!=0) res[0][303]=a03;
  if (res[0]!=0) res[0][304]=a11;
  if (res[0]!=0) res[0][305]=a04;
  if (res[0]!=0) res[0][306]=a11;
  if (res[0]!=0) res[0][307]=a05;
  if (res[0]!=0) res[0][308]=a11;
  if (res[0]!=0) res[0][309]=a06;
  if (res[0]!=0) res[0][310]=a11;
  if (res[0]!=0) res[0][311]=a07;
  if (res[0]!=0) res[0][312]=a11;
  if (res[0]!=0) res[0][313]=a08;
  if (res[0]!=0) res[0][314]=a11;
  if (res[0]!=0) res[0][315]=a09;
  if (res[0]!=0) res[0][316]=a11;
  if (res[0]!=0) res[0][317]=a11;
  if (res[0]!=0) res[0][318]=a10;
  a14=(a11+a11);
  if (res[0]!=0) res[0][319]=a14;
  if (res[0]!=0) res[0][320]=a12;
  if (res[0]!=0) res[0][321]=a11;
  if (res[0]!=0) res[0][322]=a13;
  if (res[0]!=0) res[0][323]=a11;
  if (res[0]!=0) res[0][324]=a00;
  if (res[0]!=0) res[0][325]=a12;
  if (res[0]!=0) res[0][326]=a01;
  if (res[0]!=0) res[0][327]=a12;
  if (res[0]!=0) res[0][328]=a02;
  if (res[0]!=0) res[0][329]=a12;
  if (res[0]!=0) res[0][330]=a03;
  if (res[0]!=0) res[0][331]=a12;
  if (res[0]!=0) res[0][332]=a04;
  if (res[0]!=0) res[0][333]=a12;
  if (res[0]!=0) res[0][334]=a05;
  if (res[0]!=0) res[0][335]=a12;
  if (res[0]!=0) res[0][336]=a06;
  if (res[0]!=0) res[0][337]=a12;
  if (res[0]!=0) res[0][338]=a07;
  if (res[0]!=0) res[0][339]=a12;
  if (res[0]!=0) res[0][340]=a08;
  if (res[0]!=0) res[0][341]=a12;
  if (res[0]!=0) res[0][342]=a09;
  if (res[0]!=0) res[0][343]=a12;
  if (res[0]!=0) res[0][344]=a12;
  if (res[0]!=0) res[0][345]=a10;
  if (res[0]!=0) res[0][346]=a12;
  if (res[0]!=0) res[0][347]=a11;
  a14=(a12+a12);
  if (res[0]!=0) res[0][348]=a14;
  if (res[0]!=0) res[0][349]=a13;
  if (res[0]!=0) res[0][350]=a12;
  if (res[0]!=0) res[0][351]=a00;
  if (res[0]!=0) res[0][352]=a13;
  if (res[0]!=0) res[0][353]=a01;
  if (res[0]!=0) res[0][354]=a13;
  if (res[0]!=0) res[0][355]=a02;
  if (res[0]!=0) res[0][356]=a13;
  if (res[0]!=0) res[0][357]=a03;
  if (res[0]!=0) res[0][358]=a13;
  if (res[0]!=0) res[0][359]=a04;
  if (res[0]!=0) res[0][360]=a13;
  if (res[0]!=0) res[0][361]=a05;
  if (res[0]!=0) res[0][362]=a13;
  if (res[0]!=0) res[0][363]=a06;
  if (res[0]!=0) res[0][364]=a13;
  if (res[0]!=0) res[0][365]=a07;
  if (res[0]!=0) res[0][366]=a13;
  if (res[0]!=0) res[0][367]=a08;
  if (res[0]!=0) res[0][368]=a13;
  if (res[0]!=0) res[0][369]=a09;
  if (res[0]!=0) res[0][370]=a13;
  if (res[0]!=0) res[0][371]=a13;
  if (res[0]!=0) res[0][372]=a10;
  if (res[0]!=0) res[0][373]=a13;
  if (res[0]!=0) res[0][374]=a11;
  if (res[0]!=0) res[0][375]=a13;
  if (res[0]!=0) res[0][376]=a12;
  a13=(a13+a13);
  if (res[0]!=0) res[0][377]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_hess_xu_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_hess_xu_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_hess_xu_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_hess_xu_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_hess_xu_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_hess_xu_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_hess_xu_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_hess_xu_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_hess_xu_p_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_hess_xu_p_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ocp_problem_cost_ext_cost_hess_xu_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_hess_xu_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_hess_xu_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_hess_xu_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_hess_xu_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_hess_xu_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_hess_xu_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
