/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_problem_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {461, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {14, 1, 1};

/* ocp_problem_cost_ext_cost_fun_jac:(i0[10],i1[4],i2[0],i3[0],i4[461])->(o0,o1[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133, a134, a135, a136, a137, a138, a139, a140, a141, a142, a143;
  casadi_real a144, a145, a146, a147, a148, a149, a150, a151, a152, a153, a154, a155;
  casadi_real a156, a157, a158, a159, a160, a161, a162, a163, a164, a165, a166, a167;
  casadi_real a168, a169, a170, a171, a172, a173, a174, a175, a176, a177, a178, a179;
  casadi_real a180, a181, a182, a183, a184, a185, a186, a187, a188, a189, a190, a191;
  casadi_real a192, a193, a194, a195, a196, a197, a198, a199, a200, a201, a202, a203;
  casadi_real a204, a205, a206, a207, a208, a209, a210, a211, a212, a213, a214, a215;
  casadi_real a216, a217, a218, a219, a220, a221, a222, a223, a224, a225;
  a000=arg[0]? arg[0][0] : 0;
  a001=arg[4]? arg[4][0] : 0;
  a002=(a000*a001);
  a003=arg[0]? arg[0][1] : 0;
  a004=arg[4]? arg[4][1] : 0;
  a005=(a003*a004);
  a002=(a002+a005);
  a005=arg[0]? arg[0][2] : 0;
  a006=arg[4]? arg[4][2] : 0;
  a007=(a005*a006);
  a002=(a002+a007);
  a007=arg[0]? arg[0][3] : 0;
  a008=arg[4]? arg[4][3] : 0;
  a009=(a007*a008);
  a002=(a002+a009);
  a009=arg[0]? arg[0][4] : 0;
  a010=arg[4]? arg[4][4] : 0;
  a011=(a009*a010);
  a002=(a002+a011);
  a011=arg[0]? arg[0][5] : 0;
  a012=arg[4]? arg[4][5] : 0;
  a013=(a011*a012);
  a002=(a002+a013);
  a013=arg[0]? arg[0][6] : 0;
  a014=arg[4]? arg[4][6] : 0;
  a015=(a013*a014);
  a002=(a002+a015);
  a015=arg[0]? arg[0][7] : 0;
  a016=arg[4]? arg[4][7] : 0;
  a017=(a015*a016);
  a002=(a002+a017);
  a017=arg[0]? arg[0][8] : 0;
  a018=arg[4]? arg[4][8] : 0;
  a019=(a017*a018);
  a002=(a002+a019);
  a019=arg[0]? arg[0][9] : 0;
  a020=arg[4]? arg[4][9] : 0;
  a021=(a019*a020);
  a002=(a002+a021);
  a021=arg[1]? arg[1][0] : 0;
  a022=arg[4]? arg[4][10] : 0;
  a023=(a021*a022);
  a002=(a002+a023);
  a023=arg[1]? arg[1][1] : 0;
  a024=arg[4]? arg[4][11] : 0;
  a025=(a023*a024);
  a002=(a002+a025);
  a025=arg[1]? arg[1][2] : 0;
  a026=arg[4]? arg[4][12] : 0;
  a027=(a025*a026);
  a002=(a002+a027);
  a027=arg[1]? arg[1][3] : 0;
  a028=arg[4]? arg[4][13] : 0;
  a029=(a027*a028);
  a002=(a002+a029);
  a029=(a002*a000);
  a030=arg[4]? arg[4][14] : 0;
  a031=(a000*a030);
  a032=arg[4]? arg[4][15] : 0;
  a033=(a003*a032);
  a031=(a031+a033);
  a033=arg[4]? arg[4][16] : 0;
  a034=(a005*a033);
  a031=(a031+a034);
  a034=arg[4]? arg[4][17] : 0;
  a035=(a007*a034);
  a031=(a031+a035);
  a035=arg[4]? arg[4][18] : 0;
  a036=(a009*a035);
  a031=(a031+a036);
  a036=arg[4]? arg[4][19] : 0;
  a037=(a011*a036);
  a031=(a031+a037);
  a037=arg[4]? arg[4][20] : 0;
  a038=(a013*a037);
  a031=(a031+a038);
  a038=arg[4]? arg[4][21] : 0;
  a039=(a015*a038);
  a031=(a031+a039);
  a039=arg[4]? arg[4][22] : 0;
  a040=(a017*a039);
  a031=(a031+a040);
  a040=arg[4]? arg[4][23] : 0;
  a041=(a019*a040);
  a031=(a031+a041);
  a041=arg[4]? arg[4][24] : 0;
  a042=(a021*a041);
  a031=(a031+a042);
  a042=arg[4]? arg[4][25] : 0;
  a043=(a023*a042);
  a031=(a031+a043);
  a043=arg[4]? arg[4][26] : 0;
  a044=(a025*a043);
  a031=(a031+a044);
  a044=arg[4]? arg[4][27] : 0;
  a045=(a027*a044);
  a031=(a031+a045);
  a045=(a031*a003);
  a029=(a029+a045);
  a045=arg[4]? arg[4][28] : 0;
  a046=(a000*a045);
  a047=arg[4]? arg[4][29] : 0;
  a048=(a003*a047);
  a046=(a046+a048);
  a048=arg[4]? arg[4][30] : 0;
  a049=(a005*a048);
  a046=(a046+a049);
  a049=arg[4]? arg[4][31] : 0;
  a050=(a007*a049);
  a046=(a046+a050);
  a050=arg[4]? arg[4][32] : 0;
  a051=(a009*a050);
  a046=(a046+a051);
  a051=arg[4]? arg[4][33] : 0;
  a052=(a011*a051);
  a046=(a046+a052);
  a052=arg[4]? arg[4][34] : 0;
  a053=(a013*a052);
  a046=(a046+a053);
  a053=arg[4]? arg[4][35] : 0;
  a054=(a015*a053);
  a046=(a046+a054);
  a054=arg[4]? arg[4][36] : 0;
  a055=(a017*a054);
  a046=(a046+a055);
  a055=arg[4]? arg[4][37] : 0;
  a056=(a019*a055);
  a046=(a046+a056);
  a056=arg[4]? arg[4][38] : 0;
  a057=(a021*a056);
  a046=(a046+a057);
  a057=arg[4]? arg[4][39] : 0;
  a058=(a023*a057);
  a046=(a046+a058);
  a058=arg[4]? arg[4][40] : 0;
  a059=(a025*a058);
  a046=(a046+a059);
  a059=arg[4]? arg[4][41] : 0;
  a060=(a027*a059);
  a046=(a046+a060);
  a060=(a046*a005);
  a029=(a029+a060);
  a060=arg[4]? arg[4][42] : 0;
  a061=(a000*a060);
  a062=arg[4]? arg[4][43] : 0;
  a063=(a003*a062);
  a061=(a061+a063);
  a063=arg[4]? arg[4][44] : 0;
  a064=(a005*a063);
  a061=(a061+a064);
  a064=arg[4]? arg[4][45] : 0;
  a065=(a007*a064);
  a061=(a061+a065);
  a065=arg[4]? arg[4][46] : 0;
  a066=(a009*a065);
  a061=(a061+a066);
  a066=arg[4]? arg[4][47] : 0;
  a067=(a011*a066);
  a061=(a061+a067);
  a067=arg[4]? arg[4][48] : 0;
  a068=(a013*a067);
  a061=(a061+a068);
  a068=arg[4]? arg[4][49] : 0;
  a069=(a015*a068);
  a061=(a061+a069);
  a069=arg[4]? arg[4][50] : 0;
  a070=(a017*a069);
  a061=(a061+a070);
  a070=arg[4]? arg[4][51] : 0;
  a071=(a019*a070);
  a061=(a061+a071);
  a071=arg[4]? arg[4][52] : 0;
  a072=(a021*a071);
  a061=(a061+a072);
  a072=arg[4]? arg[4][53] : 0;
  a073=(a023*a072);
  a061=(a061+a073);
  a073=arg[4]? arg[4][54] : 0;
  a074=(a025*a073);
  a061=(a061+a074);
  a074=arg[4]? arg[4][55] : 0;
  a075=(a027*a074);
  a061=(a061+a075);
  a075=(a061*a007);
  a029=(a029+a075);
  a075=arg[4]? arg[4][56] : 0;
  a076=(a000*a075);
  a077=arg[4]? arg[4][57] : 0;
  a078=(a003*a077);
  a076=(a076+a078);
  a078=arg[4]? arg[4][58] : 0;
  a079=(a005*a078);
  a076=(a076+a079);
  a079=arg[4]? arg[4][59] : 0;
  a080=(a007*a079);
  a076=(a076+a080);
  a080=arg[4]? arg[4][60] : 0;
  a081=(a009*a080);
  a076=(a076+a081);
  a081=arg[4]? arg[4][61] : 0;
  a082=(a011*a081);
  a076=(a076+a082);
  a082=arg[4]? arg[4][62] : 0;
  a083=(a013*a082);
  a076=(a076+a083);
  a083=arg[4]? arg[4][63] : 0;
  a084=(a015*a083);
  a076=(a076+a084);
  a084=arg[4]? arg[4][64] : 0;
  a085=(a017*a084);
  a076=(a076+a085);
  a085=arg[4]? arg[4][65] : 0;
  a086=(a019*a085);
  a076=(a076+a086);
  a086=arg[4]? arg[4][66] : 0;
  a087=(a021*a086);
  a076=(a076+a087);
  a087=arg[4]? arg[4][67] : 0;
  a088=(a023*a087);
  a076=(a076+a088);
  a088=arg[4]? arg[4][68] : 0;
  a089=(a025*a088);
  a076=(a076+a089);
  a089=arg[4]? arg[4][69] : 0;
  a090=(a027*a089);
  a076=(a076+a090);
  a090=(a076*a009);
  a029=(a029+a090);
  a090=arg[4]? arg[4][70] : 0;
  a091=(a000*a090);
  a092=arg[4]? arg[4][71] : 0;
  a093=(a003*a092);
  a091=(a091+a093);
  a093=arg[4]? arg[4][72] : 0;
  a094=(a005*a093);
  a091=(a091+a094);
  a094=arg[4]? arg[4][73] : 0;
  a095=(a007*a094);
  a091=(a091+a095);
  a095=arg[4]? arg[4][74] : 0;
  a096=(a009*a095);
  a091=(a091+a096);
  a096=arg[4]? arg[4][75] : 0;
  a097=(a011*a096);
  a091=(a091+a097);
  a097=arg[4]? arg[4][76] : 0;
  a098=(a013*a097);
  a091=(a091+a098);
  a098=arg[4]? arg[4][77] : 0;
  a099=(a015*a098);
  a091=(a091+a099);
  a099=arg[4]? arg[4][78] : 0;
  a100=(a017*a099);
  a091=(a091+a100);
  a100=arg[4]? arg[4][79] : 0;
  a101=(a019*a100);
  a091=(a091+a101);
  a101=arg[4]? arg[4][80] : 0;
  a102=(a021*a101);
  a091=(a091+a102);
  a102=arg[4]? arg[4][81] : 0;
  a103=(a023*a102);
  a091=(a091+a103);
  a103=arg[4]? arg[4][82] : 0;
  a104=(a025*a103);
  a091=(a091+a104);
  a104=arg[4]? arg[4][83] : 0;
  a105=(a027*a104);
  a091=(a091+a105);
  a105=(a091*a011);
  a029=(a029+a105);
  a105=arg[4]? arg[4][84] : 0;
  a106=(a000*a105);
  a107=arg[4]? arg[4][85] : 0;
  a108=(a003*a107);
  a106=(a106+a108);
  a108=arg[4]? arg[4][86] : 0;
  a109=(a005*a108);
  a106=(a106+a109);
  a109=arg[4]? arg[4][87] : 0;
  a110=(a007*a109);
  a106=(a106+a110);
  a110=arg[4]? arg[4][88] : 0;
  a111=(a009*a110);
  a106=(a106+a111);
  a111=arg[4]? arg[4][89] : 0;
  a112=(a011*a111);
  a106=(a106+a112);
  a112=arg[4]? arg[4][90] : 0;
  a113=(a013*a112);
  a106=(a106+a113);
  a113=arg[4]? arg[4][91] : 0;
  a114=(a015*a113);
  a106=(a106+a114);
  a114=arg[4]? arg[4][92] : 0;
  a115=(a017*a114);
  a106=(a106+a115);
  a115=arg[4]? arg[4][93] : 0;
  a116=(a019*a115);
  a106=(a106+a116);
  a116=arg[4]? arg[4][94] : 0;
  a117=(a021*a116);
  a106=(a106+a117);
  a117=arg[4]? arg[4][95] : 0;
  a118=(a023*a117);
  a106=(a106+a118);
  a118=arg[4]? arg[4][96] : 0;
  a119=(a025*a118);
  a106=(a106+a119);
  a119=arg[4]? arg[4][97] : 0;
  a120=(a027*a119);
  a106=(a106+a120);
  a120=(a106*a013);
  a029=(a029+a120);
  a120=arg[4]? arg[4][98] : 0;
  a121=(a000*a120);
  a122=arg[4]? arg[4][99] : 0;
  a123=(a003*a122);
  a121=(a121+a123);
  a123=arg[4]? arg[4][100] : 0;
  a124=(a005*a123);
  a121=(a121+a124);
  a124=arg[4]? arg[4][101] : 0;
  a125=(a007*a124);
  a121=(a121+a125);
  a125=arg[4]? arg[4][102] : 0;
  a126=(a009*a125);
  a121=(a121+a126);
  a126=arg[4]? arg[4][103] : 0;
  a127=(a011*a126);
  a121=(a121+a127);
  a127=arg[4]? arg[4][104] : 0;
  a128=(a013*a127);
  a121=(a121+a128);
  a128=arg[4]? arg[4][105] : 0;
  a129=(a015*a128);
  a121=(a121+a129);
  a129=arg[4]? arg[4][106] : 0;
  a130=(a017*a129);
  a121=(a121+a130);
  a130=arg[4]? arg[4][107] : 0;
  a131=(a019*a130);
  a121=(a121+a131);
  a131=arg[4]? arg[4][108] : 0;
  a132=(a021*a131);
  a121=(a121+a132);
  a132=arg[4]? arg[4][109] : 0;
  a133=(a023*a132);
  a121=(a121+a133);
  a133=arg[4]? arg[4][110] : 0;
  a134=(a025*a133);
  a121=(a121+a134);
  a134=arg[4]? arg[4][111] : 0;
  a135=(a027*a134);
  a121=(a121+a135);
  a135=(a121*a015);
  a029=(a029+a135);
  a135=arg[4]? arg[4][112] : 0;
  a136=(a000*a135);
  a137=arg[4]? arg[4][113] : 0;
  a138=(a003*a137);
  a136=(a136+a138);
  a138=arg[4]? arg[4][114] : 0;
  a139=(a005*a138);
  a136=(a136+a139);
  a139=arg[4]? arg[4][115] : 0;
  a140=(a007*a139);
  a136=(a136+a140);
  a140=arg[4]? arg[4][116] : 0;
  a141=(a009*a140);
  a136=(a136+a141);
  a141=arg[4]? arg[4][117] : 0;
  a142=(a011*a141);
  a136=(a136+a142);
  a142=arg[4]? arg[4][118] : 0;
  a143=(a013*a142);
  a136=(a136+a143);
  a143=arg[4]? arg[4][119] : 0;
  a144=(a015*a143);
  a136=(a136+a144);
  a144=arg[4]? arg[4][120] : 0;
  a145=(a017*a144);
  a136=(a136+a145);
  a145=arg[4]? arg[4][121] : 0;
  a146=(a019*a145);
  a136=(a136+a146);
  a146=arg[4]? arg[4][122] : 0;
  a147=(a021*a146);
  a136=(a136+a147);
  a147=arg[4]? arg[4][123] : 0;
  a148=(a023*a147);
  a136=(a136+a148);
  a148=arg[4]? arg[4][124] : 0;
  a149=(a025*a148);
  a136=(a136+a149);
  a149=arg[4]? arg[4][125] : 0;
  a150=(a027*a149);
  a136=(a136+a150);
  a150=(a136*a017);
  a029=(a029+a150);
  a150=arg[4]? arg[4][126] : 0;
  a151=(a000*a150);
  a152=arg[4]? arg[4][127] : 0;
  a153=(a003*a152);
  a151=(a151+a153);
  a153=arg[4]? arg[4][128] : 0;
  a154=(a005*a153);
  a151=(a151+a154);
  a154=arg[4]? arg[4][129] : 0;
  a155=(a007*a154);
  a151=(a151+a155);
  a155=arg[4]? arg[4][130] : 0;
  a156=(a009*a155);
  a151=(a151+a156);
  a156=arg[4]? arg[4][131] : 0;
  a157=(a011*a156);
  a151=(a151+a157);
  a157=arg[4]? arg[4][132] : 0;
  a158=(a013*a157);
  a151=(a151+a158);
  a158=arg[4]? arg[4][133] : 0;
  a159=(a015*a158);
  a151=(a151+a159);
  a159=arg[4]? arg[4][134] : 0;
  a160=(a017*a159);
  a151=(a151+a160);
  a160=arg[4]? arg[4][135] : 0;
  a161=(a019*a160);
  a151=(a151+a161);
  a161=arg[4]? arg[4][136] : 0;
  a162=(a021*a161);
  a151=(a151+a162);
  a162=arg[4]? arg[4][137] : 0;
  a163=(a023*a162);
  a151=(a151+a163);
  a163=arg[4]? arg[4][138] : 0;
  a164=(a025*a163);
  a151=(a151+a164);
  a164=arg[4]? arg[4][139] : 0;
  a165=(a027*a164);
  a151=(a151+a165);
  a165=(a151*a019);
  a029=(a029+a165);
  a165=arg[4]? arg[4][140] : 0;
  a166=(a000*a165);
  a167=arg[4]? arg[4][141] : 0;
  a168=(a003*a167);
  a166=(a166+a168);
  a168=arg[4]? arg[4][142] : 0;
  a169=(a005*a168);
  a166=(a166+a169);
  a169=arg[4]? arg[4][143] : 0;
  a170=(a007*a169);
  a166=(a166+a170);
  a170=arg[4]? arg[4][144] : 0;
  a171=(a009*a170);
  a166=(a166+a171);
  a171=arg[4]? arg[4][145] : 0;
  a172=(a011*a171);
  a166=(a166+a172);
  a172=arg[4]? arg[4][146] : 0;
  a173=(a013*a172);
  a166=(a166+a173);
  a173=arg[4]? arg[4][147] : 0;
  a174=(a015*a173);
  a166=(a166+a174);
  a174=arg[4]? arg[4][148] : 0;
  a175=(a017*a174);
  a166=(a166+a175);
  a175=arg[4]? arg[4][149] : 0;
  a176=(a019*a175);
  a166=(a166+a176);
  a176=arg[4]? arg[4][150] : 0;
  a177=(a021*a176);
  a166=(a166+a177);
  a177=arg[4]? arg[4][151] : 0;
  a178=(a023*a177);
  a166=(a166+a178);
  a178=arg[4]? arg[4][152] : 0;
  a179=(a025*a178);
  a166=(a166+a179);
  a179=arg[4]? arg[4][153] : 0;
  a180=(a027*a179);
  a166=(a166+a180);
  a180=(a166*a021);
  a029=(a029+a180);
  a180=arg[4]? arg[4][154] : 0;
  a181=(a000*a180);
  a182=arg[4]? arg[4][155] : 0;
  a183=(a003*a182);
  a181=(a181+a183);
  a183=arg[4]? arg[4][156] : 0;
  a184=(a005*a183);
  a181=(a181+a184);
  a184=arg[4]? arg[4][157] : 0;
  a185=(a007*a184);
  a181=(a181+a185);
  a185=arg[4]? arg[4][158] : 0;
  a186=(a009*a185);
  a181=(a181+a186);
  a186=arg[4]? arg[4][159] : 0;
  a187=(a011*a186);
  a181=(a181+a187);
  a187=arg[4]? arg[4][160] : 0;
  a188=(a013*a187);
  a181=(a181+a188);
  a188=arg[4]? arg[4][161] : 0;
  a189=(a015*a188);
  a181=(a181+a189);
  a189=arg[4]? arg[4][162] : 0;
  a190=(a017*a189);
  a181=(a181+a190);
  a190=arg[4]? arg[4][163] : 0;
  a191=(a019*a190);
  a181=(a181+a191);
  a191=arg[4]? arg[4][164] : 0;
  a192=(a021*a191);
  a181=(a181+a192);
  a192=arg[4]? arg[4][165] : 0;
  a193=(a023*a192);
  a181=(a181+a193);
  a193=arg[4]? arg[4][166] : 0;
  a194=(a025*a193);
  a181=(a181+a194);
  a194=arg[4]? arg[4][167] : 0;
  a195=(a027*a194);
  a181=(a181+a195);
  a195=(a181*a023);
  a029=(a029+a195);
  a195=arg[4]? arg[4][168] : 0;
  a196=(a000*a195);
  a197=arg[4]? arg[4][169] : 0;
  a198=(a003*a197);
  a196=(a196+a198);
  a198=arg[4]? arg[4][170] : 0;
  a199=(a005*a198);
  a196=(a196+a199);
  a199=arg[4]? arg[4][171] : 0;
  a200=(a007*a199);
  a196=(a196+a200);
  a200=arg[4]? arg[4][172] : 0;
  a201=(a009*a200);
  a196=(a196+a201);
  a201=arg[4]? arg[4][173] : 0;
  a202=(a011*a201);
  a196=(a196+a202);
  a202=arg[4]? arg[4][174] : 0;
  a203=(a013*a202);
  a196=(a196+a203);
  a203=arg[4]? arg[4][175] : 0;
  a204=(a015*a203);
  a196=(a196+a204);
  a204=arg[4]? arg[4][176] : 0;
  a205=(a017*a204);
  a196=(a196+a205);
  a205=arg[4]? arg[4][177] : 0;
  a206=(a019*a205);
  a196=(a196+a206);
  a206=arg[4]? arg[4][178] : 0;
  a207=(a021*a206);
  a196=(a196+a207);
  a207=arg[4]? arg[4][179] : 0;
  a208=(a023*a207);
  a196=(a196+a208);
  a208=arg[4]? arg[4][180] : 0;
  a209=(a025*a208);
  a196=(a196+a209);
  a209=arg[4]? arg[4][181] : 0;
  a210=(a027*a209);
  a196=(a196+a210);
  a210=(a196*a025);
  a029=(a029+a210);
  a210=arg[4]? arg[4][182] : 0;
  a211=(a000*a210);
  a212=arg[4]? arg[4][183] : 0;
  a213=(a003*a212);
  a211=(a211+a213);
  a213=arg[4]? arg[4][184] : 0;
  a214=(a005*a213);
  a211=(a211+a214);
  a214=arg[4]? arg[4][185] : 0;
  a215=(a007*a214);
  a211=(a211+a215);
  a215=arg[4]? arg[4][186] : 0;
  a216=(a009*a215);
  a211=(a211+a216);
  a216=arg[4]? arg[4][187] : 0;
  a217=(a011*a216);
  a211=(a211+a217);
  a217=arg[4]? arg[4][188] : 0;
  a218=(a013*a217);
  a211=(a211+a218);
  a218=arg[4]? arg[4][189] : 0;
  a219=(a015*a218);
  a211=(a211+a219);
  a219=arg[4]? arg[4][190] : 0;
  a220=(a017*a219);
  a211=(a211+a220);
  a220=arg[4]? arg[4][191] : 0;
  a221=(a019*a220);
  a211=(a211+a221);
  a221=arg[4]? arg[4][192] : 0;
  a222=(a021*a221);
  a211=(a211+a222);
  a222=arg[4]? arg[4][193] : 0;
  a223=(a023*a222);
  a211=(a211+a223);
  a223=arg[4]? arg[4][194] : 0;
  a224=(a025*a223);
  a211=(a211+a224);
  a224=arg[4]? arg[4][195] : 0;
  a225=(a027*a224);
  a211=(a211+a225);
  a225=(a211*a027);
  a029=(a029+a225);
  if (res[0]!=0) res[0][0]=a029;
  a221=(a221*a027);
  a206=(a206*a025);
  a221=(a221+a206);
  a191=(a191*a023);
  a221=(a221+a191);
  a221=(a221+a166);
  a176=(a176*a021);
  a221=(a221+a176);
  a161=(a161*a019);
  a221=(a221+a161);
  a146=(a146*a017);
  a221=(a221+a146);
  a131=(a131*a015);
  a221=(a221+a131);
  a116=(a116*a013);
  a221=(a221+a116);
  a101=(a101*a011);
  a221=(a221+a101);
  a086=(a086*a009);
  a221=(a221+a086);
  a071=(a071*a007);
  a221=(a221+a071);
  a056=(a056*a005);
  a221=(a221+a056);
  a041=(a041*a003);
  a221=(a221+a041);
  a022=(a022*a000);
  a221=(a221+a022);
  if (res[1]!=0) res[1][0]=a221;
  a222=(a222*a027);
  a207=(a207*a025);
  a222=(a222+a207);
  a222=(a222+a181);
  a192=(a192*a023);
  a222=(a222+a192);
  a177=(a177*a021);
  a222=(a222+a177);
  a162=(a162*a019);
  a222=(a222+a162);
  a147=(a147*a017);
  a222=(a222+a147);
  a132=(a132*a015);
  a222=(a222+a132);
  a117=(a117*a013);
  a222=(a222+a117);
  a102=(a102*a011);
  a222=(a222+a102);
  a087=(a087*a009);
  a222=(a222+a087);
  a072=(a072*a007);
  a222=(a222+a072);
  a057=(a057*a005);
  a222=(a222+a057);
  a042=(a042*a003);
  a222=(a222+a042);
  a024=(a024*a000);
  a222=(a222+a024);
  if (res[1]!=0) res[1][1]=a222;
  a223=(a223*a027);
  a223=(a223+a196);
  a208=(a208*a025);
  a223=(a223+a208);
  a193=(a193*a023);
  a223=(a223+a193);
  a178=(a178*a021);
  a223=(a223+a178);
  a163=(a163*a019);
  a223=(a223+a163);
  a148=(a148*a017);
  a223=(a223+a148);
  a133=(a133*a015);
  a223=(a223+a133);
  a118=(a118*a013);
  a223=(a223+a118);
  a103=(a103*a011);
  a223=(a223+a103);
  a088=(a088*a009);
  a223=(a223+a088);
  a073=(a073*a007);
  a223=(a223+a073);
  a058=(a058*a005);
  a223=(a223+a058);
  a043=(a043*a003);
  a223=(a223+a043);
  a026=(a026*a000);
  a223=(a223+a026);
  if (res[1]!=0) res[1][2]=a223;
  a224=(a224*a027);
  a211=(a211+a224);
  a209=(a209*a025);
  a211=(a211+a209);
  a194=(a194*a023);
  a211=(a211+a194);
  a179=(a179*a021);
  a211=(a211+a179);
  a164=(a164*a019);
  a211=(a211+a164);
  a149=(a149*a017);
  a211=(a211+a149);
  a134=(a134*a015);
  a211=(a211+a134);
  a119=(a119*a013);
  a211=(a211+a119);
  a104=(a104*a011);
  a211=(a211+a104);
  a089=(a089*a009);
  a211=(a211+a089);
  a074=(a074*a007);
  a211=(a211+a074);
  a059=(a059*a005);
  a211=(a211+a059);
  a044=(a044*a003);
  a211=(a211+a044);
  a028=(a028*a000);
  a211=(a211+a028);
  if (res[1]!=0) res[1][3]=a211;
  a210=(a210*a027);
  a195=(a195*a025);
  a210=(a210+a195);
  a180=(a180*a023);
  a210=(a210+a180);
  a165=(a165*a021);
  a210=(a210+a165);
  a150=(a150*a019);
  a210=(a210+a150);
  a135=(a135*a017);
  a210=(a210+a135);
  a120=(a120*a015);
  a210=(a210+a120);
  a105=(a105*a013);
  a210=(a210+a105);
  a090=(a090*a011);
  a210=(a210+a090);
  a075=(a075*a009);
  a210=(a210+a075);
  a060=(a060*a007);
  a210=(a210+a060);
  a045=(a045*a005);
  a210=(a210+a045);
  a030=(a030*a003);
  a210=(a210+a030);
  a210=(a210+a002);
  a001=(a001*a000);
  a210=(a210+a001);
  if (res[1]!=0) res[1][4]=a210;
  a212=(a212*a027);
  a197=(a197*a025);
  a212=(a212+a197);
  a182=(a182*a023);
  a212=(a212+a182);
  a167=(a167*a021);
  a212=(a212+a167);
  a152=(a152*a019);
  a212=(a212+a152);
  a137=(a137*a017);
  a212=(a212+a137);
  a122=(a122*a015);
  a212=(a212+a122);
  a107=(a107*a013);
  a212=(a212+a107);
  a092=(a092*a011);
  a212=(a212+a092);
  a077=(a077*a009);
  a212=(a212+a077);
  a062=(a062*a007);
  a212=(a212+a062);
  a047=(a047*a005);
  a212=(a212+a047);
  a212=(a212+a031);
  a032=(a032*a003);
  a212=(a212+a032);
  a004=(a004*a000);
  a212=(a212+a004);
  if (res[1]!=0) res[1][5]=a212;
  a213=(a213*a027);
  a198=(a198*a025);
  a213=(a213+a198);
  a183=(a183*a023);
  a213=(a213+a183);
  a168=(a168*a021);
  a213=(a213+a168);
  a153=(a153*a019);
  a213=(a213+a153);
  a138=(a138*a017);
  a213=(a213+a138);
  a123=(a123*a015);
  a213=(a213+a123);
  a108=(a108*a013);
  a213=(a213+a108);
  a093=(a093*a011);
  a213=(a213+a093);
  a078=(a078*a009);
  a213=(a213+a078);
  a063=(a063*a007);
  a213=(a213+a063);
  a213=(a213+a046);
  a048=(a048*a005);
  a213=(a213+a048);
  a033=(a033*a003);
  a213=(a213+a033);
  a006=(a006*a000);
  a213=(a213+a006);
  if (res[1]!=0) res[1][6]=a213;
  a214=(a214*a027);
  a199=(a199*a025);
  a214=(a214+a199);
  a184=(a184*a023);
  a214=(a214+a184);
  a169=(a169*a021);
  a214=(a214+a169);
  a154=(a154*a019);
  a214=(a214+a154);
  a139=(a139*a017);
  a214=(a214+a139);
  a124=(a124*a015);
  a214=(a214+a124);
  a109=(a109*a013);
  a214=(a214+a109);
  a094=(a094*a011);
  a214=(a214+a094);
  a079=(a079*a009);
  a214=(a214+a079);
  a214=(a214+a061);
  a064=(a064*a007);
  a214=(a214+a064);
  a049=(a049*a005);
  a214=(a214+a049);
  a034=(a034*a003);
  a214=(a214+a034);
  a008=(a008*a000);
  a214=(a214+a008);
  if (res[1]!=0) res[1][7]=a214;
  a215=(a215*a027);
  a200=(a200*a025);
  a215=(a215+a200);
  a185=(a185*a023);
  a215=(a215+a185);
  a170=(a170*a021);
  a215=(a215+a170);
  a155=(a155*a019);
  a215=(a215+a155);
  a140=(a140*a017);
  a215=(a215+a140);
  a125=(a125*a015);
  a215=(a215+a125);
  a110=(a110*a013);
  a215=(a215+a110);
  a095=(a095*a011);
  a215=(a215+a095);
  a215=(a215+a076);
  a080=(a080*a009);
  a215=(a215+a080);
  a065=(a065*a007);
  a215=(a215+a065);
  a050=(a050*a005);
  a215=(a215+a050);
  a035=(a035*a003);
  a215=(a215+a035);
  a010=(a010*a000);
  a215=(a215+a010);
  if (res[1]!=0) res[1][8]=a215;
  a216=(a216*a027);
  a201=(a201*a025);
  a216=(a216+a201);
  a186=(a186*a023);
  a216=(a216+a186);
  a171=(a171*a021);
  a216=(a216+a171);
  a156=(a156*a019);
  a216=(a216+a156);
  a141=(a141*a017);
  a216=(a216+a141);
  a126=(a126*a015);
  a216=(a216+a126);
  a111=(a111*a013);
  a216=(a216+a111);
  a216=(a216+a091);
  a096=(a096*a011);
  a216=(a216+a096);
  a081=(a081*a009);
  a216=(a216+a081);
  a066=(a066*a007);
  a216=(a216+a066);
  a051=(a051*a005);
  a216=(a216+a051);
  a036=(a036*a003);
  a216=(a216+a036);
  a012=(a012*a000);
  a216=(a216+a012);
  if (res[1]!=0) res[1][9]=a216;
  a217=(a217*a027);
  a202=(a202*a025);
  a217=(a217+a202);
  a187=(a187*a023);
  a217=(a217+a187);
  a172=(a172*a021);
  a217=(a217+a172);
  a157=(a157*a019);
  a217=(a217+a157);
  a142=(a142*a017);
  a217=(a217+a142);
  a127=(a127*a015);
  a217=(a217+a127);
  a217=(a217+a106);
  a112=(a112*a013);
  a217=(a217+a112);
  a097=(a097*a011);
  a217=(a217+a097);
  a082=(a082*a009);
  a217=(a217+a082);
  a067=(a067*a007);
  a217=(a217+a067);
  a052=(a052*a005);
  a217=(a217+a052);
  a037=(a037*a003);
  a217=(a217+a037);
  a014=(a014*a000);
  a217=(a217+a014);
  if (res[1]!=0) res[1][10]=a217;
  a218=(a218*a027);
  a203=(a203*a025);
  a218=(a218+a203);
  a188=(a188*a023);
  a218=(a218+a188);
  a173=(a173*a021);
  a218=(a218+a173);
  a158=(a158*a019);
  a218=(a218+a158);
  a143=(a143*a017);
  a218=(a218+a143);
  a218=(a218+a121);
  a128=(a128*a015);
  a218=(a218+a128);
  a113=(a113*a013);
  a218=(a218+a113);
  a098=(a098*a011);
  a218=(a218+a098);
  a083=(a083*a009);
  a218=(a218+a083);
  a068=(a068*a007);
  a218=(a218+a068);
  a053=(a053*a005);
  a218=(a218+a053);
  a038=(a038*a003);
  a218=(a218+a038);
  a016=(a016*a000);
  a218=(a218+a016);
  if (res[1]!=0) res[1][11]=a218;
  a219=(a219*a027);
  a204=(a204*a025);
  a219=(a219+a204);
  a189=(a189*a023);
  a219=(a219+a189);
  a174=(a174*a021);
  a219=(a219+a174);
  a159=(a159*a019);
  a219=(a219+a159);
  a219=(a219+a136);
  a144=(a144*a017);
  a219=(a219+a144);
  a129=(a129*a015);
  a219=(a219+a129);
  a114=(a114*a013);
  a219=(a219+a114);
  a099=(a099*a011);
  a219=(a219+a099);
  a084=(a084*a009);
  a219=(a219+a084);
  a069=(a069*a007);
  a219=(a219+a069);
  a054=(a054*a005);
  a219=(a219+a054);
  a039=(a039*a003);
  a219=(a219+a039);
  a018=(a018*a000);
  a219=(a219+a018);
  if (res[1]!=0) res[1][12]=a219;
  a220=(a220*a027);
  a205=(a205*a025);
  a220=(a220+a205);
  a190=(a190*a023);
  a220=(a220+a190);
  a175=(a175*a021);
  a220=(a220+a175);
  a220=(a220+a151);
  a160=(a160*a019);
  a220=(a220+a160);
  a145=(a145*a017);
  a220=(a220+a145);
  a130=(a130*a015);
  a220=(a220+a130);
  a115=(a115*a013);
  a220=(a220+a115);
  a100=(a100*a011);
  a220=(a220+a100);
  a085=(a085*a009);
  a220=(a220+a085);
  a070=(a070*a007);
  a220=(a220+a070);
  a055=(a055*a005);
  a220=(a220+a055);
  a040=(a040*a003);
  a220=(a220+a040);
  a020=(a020*a000);
  a220=(a220+a020);
  if (res[1]!=0) res[1][13]=a220;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_fun_jac_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ocp_problem_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
