/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_problem_cost_ext_cost_e_hess_xu_p_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {461, 1, 1};
static const casadi_int casadi_s3[389] = 
  {10, 196, 0, 1, 3, 5, 7, 9,
  11, 13, 15, 17, 19, 19, 19, 19,
  19, 21, 22, 24, 26, 28, 30, 32,
  34, 36, 38, 38, 38, 38, 38, 40,
  42, 43, 45, 47, 49, 51, 53, 55,
  57, 57, 57, 57, 57, 59, 61, 63,
  64, 66, 68, 70, 72, 74, 76, 76,
  76, 76, 76, 78, 80, 82, 84, 85,
  87, 89, 91, 93, 95, 95, 95, 95,
  95, 97, 99, 101, 103, 105, 106, 108,
  110, 112, 114, 114, 114, 114, 114, 116,
  118, 120, 122, 124, 126, 127, 129, 131,
  133, 133, 133, 133, 133, 135, 137, 139,
  141, 143, 145, 147, 148, 150, 152, 152,
  152, 152, 152, 154, 156, 158, 160, 162,
  164, 166, 168, 169, 171, 171, 171, 171,
  171, 173, 175, 177, 179, 181, 183, 185,
  187, 189, 190, 190, 190, 190, 190, 190,
  190, 190, 190, 190, 190, 190, 190, 190,
  190, 190, 190, 190, 190, 190, 190, 190,
  190, 190, 190, 190, 190, 190, 190, 190,
  190, 190, 190, 190, 190, 190, 190, 190,
  190, 190, 190, 190, 190, 190, 190, 190,
  190, 190, 190, 190, 190, 190, 190, 190,
  190, 190, 190, 190, 190, 190, 190, 0,
  0, 1, 0, 2, 0, 3, 0, 4,
  0, 5, 0, 6, 0, 7, 0, 8,
  0, 9, 0, 1, 1, 1, 2, 1,
  3, 1, 4, 1, 5, 1, 6, 1,
  7, 1, 8, 1, 9, 0, 2, 1,
  2, 2, 2, 3, 2, 4, 2, 5,
  2, 6, 2, 7, 2, 8, 2, 9,
  0, 3, 1, 3, 2, 3, 3, 3,
  4, 3, 5, 3, 6, 3, 7, 3,
  8, 3, 9, 0, 4, 1, 4, 2,
  4, 3, 4, 4, 4, 5, 4, 6,
  4, 7, 4, 8, 4, 9, 0, 5,
  1, 5, 2, 5, 3, 5, 4, 5,
  5, 5, 6, 5, 7, 5, 8, 5,
  9, 0, 6, 1, 6, 2, 6, 3,
  6, 4, 6, 5, 6, 6, 6, 7,
  6, 8, 6, 9, 0, 7, 1, 7,
  2, 7, 3, 7, 4, 7, 5, 7,
  6, 7, 7, 7, 8, 7, 9, 0,
  8, 1, 8, 2, 8, 3, 8, 4,
  8, 5, 8, 6, 8, 7, 8, 8,
  8, 9, 0, 9, 1, 9, 2, 9,
  3, 9, 4, 9, 5, 9, 6, 9,
  7, 9, 8, 9, 9};

/* ocp_problem_cost_ext_cost_e_hess_xu_p:(i0[10],i1[0],i2[0],i3[0],i4[461])->(o0[10x196,190nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10;
  a00=arg[0]? arg[0][0] : 0;
  a01=(a00+a00);
  if (res[0]!=0) res[0][0]=a01;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  if (res[0]!=0) res[0][2]=a00;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][3]=a02;
  if (res[0]!=0) res[0][4]=a00;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][5]=a03;
  if (res[0]!=0) res[0][6]=a00;
  a04=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][7]=a04;
  if (res[0]!=0) res[0][8]=a00;
  a05=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][9]=a05;
  if (res[0]!=0) res[0][10]=a00;
  a06=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][11]=a06;
  if (res[0]!=0) res[0][12]=a00;
  a07=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][13]=a07;
  if (res[0]!=0) res[0][14]=a00;
  a08=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][15]=a08;
  if (res[0]!=0) res[0][16]=a00;
  a09=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][17]=a09;
  if (res[0]!=0) res[0][18]=a00;
  if (res[0]!=0) res[0][19]=a01;
  if (res[0]!=0) res[0][20]=a00;
  a10=(a01+a01);
  if (res[0]!=0) res[0][21]=a10;
  if (res[0]!=0) res[0][22]=a02;
  if (res[0]!=0) res[0][23]=a01;
  if (res[0]!=0) res[0][24]=a03;
  if (res[0]!=0) res[0][25]=a01;
  if (res[0]!=0) res[0][26]=a04;
  if (res[0]!=0) res[0][27]=a01;
  if (res[0]!=0) res[0][28]=a05;
  if (res[0]!=0) res[0][29]=a01;
  if (res[0]!=0) res[0][30]=a06;
  if (res[0]!=0) res[0][31]=a01;
  if (res[0]!=0) res[0][32]=a07;
  if (res[0]!=0) res[0][33]=a01;
  if (res[0]!=0) res[0][34]=a08;
  if (res[0]!=0) res[0][35]=a01;
  if (res[0]!=0) res[0][36]=a09;
  if (res[0]!=0) res[0][37]=a01;
  if (res[0]!=0) res[0][38]=a02;
  if (res[0]!=0) res[0][39]=a00;
  if (res[0]!=0) res[0][40]=a02;
  if (res[0]!=0) res[0][41]=a01;
  a10=(a02+a02);
  if (res[0]!=0) res[0][42]=a10;
  if (res[0]!=0) res[0][43]=a03;
  if (res[0]!=0) res[0][44]=a02;
  if (res[0]!=0) res[0][45]=a04;
  if (res[0]!=0) res[0][46]=a02;
  if (res[0]!=0) res[0][47]=a05;
  if (res[0]!=0) res[0][48]=a02;
  if (res[0]!=0) res[0][49]=a06;
  if (res[0]!=0) res[0][50]=a02;
  if (res[0]!=0) res[0][51]=a07;
  if (res[0]!=0) res[0][52]=a02;
  if (res[0]!=0) res[0][53]=a08;
  if (res[0]!=0) res[0][54]=a02;
  if (res[0]!=0) res[0][55]=a09;
  if (res[0]!=0) res[0][56]=a02;
  if (res[0]!=0) res[0][57]=a03;
  if (res[0]!=0) res[0][58]=a00;
  if (res[0]!=0) res[0][59]=a03;
  if (res[0]!=0) res[0][60]=a01;
  if (res[0]!=0) res[0][61]=a03;
  if (res[0]!=0) res[0][62]=a02;
  a10=(a03+a03);
  if (res[0]!=0) res[0][63]=a10;
  if (res[0]!=0) res[0][64]=a04;
  if (res[0]!=0) res[0][65]=a03;
  if (res[0]!=0) res[0][66]=a05;
  if (res[0]!=0) res[0][67]=a03;
  if (res[0]!=0) res[0][68]=a06;
  if (res[0]!=0) res[0][69]=a03;
  if (res[0]!=0) res[0][70]=a07;
  if (res[0]!=0) res[0][71]=a03;
  if (res[0]!=0) res[0][72]=a08;
  if (res[0]!=0) res[0][73]=a03;
  if (res[0]!=0) res[0][74]=a09;
  if (res[0]!=0) res[0][75]=a03;
  if (res[0]!=0) res[0][76]=a04;
  if (res[0]!=0) res[0][77]=a00;
  if (res[0]!=0) res[0][78]=a04;
  if (res[0]!=0) res[0][79]=a01;
  if (res[0]!=0) res[0][80]=a04;
  if (res[0]!=0) res[0][81]=a02;
  if (res[0]!=0) res[0][82]=a04;
  if (res[0]!=0) res[0][83]=a03;
  a10=(a04+a04);
  if (res[0]!=0) res[0][84]=a10;
  if (res[0]!=0) res[0][85]=a05;
  if (res[0]!=0) res[0][86]=a04;
  if (res[0]!=0) res[0][87]=a06;
  if (res[0]!=0) res[0][88]=a04;
  if (res[0]!=0) res[0][89]=a07;
  if (res[0]!=0) res[0][90]=a04;
  if (res[0]!=0) res[0][91]=a08;
  if (res[0]!=0) res[0][92]=a04;
  if (res[0]!=0) res[0][93]=a09;
  if (res[0]!=0) res[0][94]=a04;
  if (res[0]!=0) res[0][95]=a05;
  if (res[0]!=0) res[0][96]=a00;
  if (res[0]!=0) res[0][97]=a05;
  if (res[0]!=0) res[0][98]=a01;
  if (res[0]!=0) res[0][99]=a05;
  if (res[0]!=0) res[0][100]=a02;
  if (res[0]!=0) res[0][101]=a05;
  if (res[0]!=0) res[0][102]=a03;
  if (res[0]!=0) res[0][103]=a05;
  if (res[0]!=0) res[0][104]=a04;
  a10=(a05+a05);
  if (res[0]!=0) res[0][105]=a10;
  if (res[0]!=0) res[0][106]=a06;
  if (res[0]!=0) res[0][107]=a05;
  if (res[0]!=0) res[0][108]=a07;
  if (res[0]!=0) res[0][109]=a05;
  if (res[0]!=0) res[0][110]=a08;
  if (res[0]!=0) res[0][111]=a05;
  if (res[0]!=0) res[0][112]=a09;
  if (res[0]!=0) res[0][113]=a05;
  if (res[0]!=0) res[0][114]=a06;
  if (res[0]!=0) res[0][115]=a00;
  if (res[0]!=0) res[0][116]=a06;
  if (res[0]!=0) res[0][117]=a01;
  if (res[0]!=0) res[0][118]=a06;
  if (res[0]!=0) res[0][119]=a02;
  if (res[0]!=0) res[0][120]=a06;
  if (res[0]!=0) res[0][121]=a03;
  if (res[0]!=0) res[0][122]=a06;
  if (res[0]!=0) res[0][123]=a04;
  if (res[0]!=0) res[0][124]=a06;
  if (res[0]!=0) res[0][125]=a05;
  a10=(a06+a06);
  if (res[0]!=0) res[0][126]=a10;
  if (res[0]!=0) res[0][127]=a07;
  if (res[0]!=0) res[0][128]=a06;
  if (res[0]!=0) res[0][129]=a08;
  if (res[0]!=0) res[0][130]=a06;
  if (res[0]!=0) res[0][131]=a09;
  if (res[0]!=0) res[0][132]=a06;
  if (res[0]!=0) res[0][133]=a07;
  if (res[0]!=0) res[0][134]=a00;
  if (res[0]!=0) res[0][135]=a07;
  if (res[0]!=0) res[0][136]=a01;
  if (res[0]!=0) res[0][137]=a07;
  if (res[0]!=0) res[0][138]=a02;
  if (res[0]!=0) res[0][139]=a07;
  if (res[0]!=0) res[0][140]=a03;
  if (res[0]!=0) res[0][141]=a07;
  if (res[0]!=0) res[0][142]=a04;
  if (res[0]!=0) res[0][143]=a07;
  if (res[0]!=0) res[0][144]=a05;
  if (res[0]!=0) res[0][145]=a07;
  if (res[0]!=0) res[0][146]=a06;
  a10=(a07+a07);
  if (res[0]!=0) res[0][147]=a10;
  if (res[0]!=0) res[0][148]=a08;
  if (res[0]!=0) res[0][149]=a07;
  if (res[0]!=0) res[0][150]=a09;
  if (res[0]!=0) res[0][151]=a07;
  if (res[0]!=0) res[0][152]=a08;
  if (res[0]!=0) res[0][153]=a00;
  if (res[0]!=0) res[0][154]=a08;
  if (res[0]!=0) res[0][155]=a01;
  if (res[0]!=0) res[0][156]=a08;
  if (res[0]!=0) res[0][157]=a02;
  if (res[0]!=0) res[0][158]=a08;
  if (res[0]!=0) res[0][159]=a03;
  if (res[0]!=0) res[0][160]=a08;
  if (res[0]!=0) res[0][161]=a04;
  if (res[0]!=0) res[0][162]=a08;
  if (res[0]!=0) res[0][163]=a05;
  if (res[0]!=0) res[0][164]=a08;
  if (res[0]!=0) res[0][165]=a06;
  if (res[0]!=0) res[0][166]=a08;
  if (res[0]!=0) res[0][167]=a07;
  a10=(a08+a08);
  if (res[0]!=0) res[0][168]=a10;
  if (res[0]!=0) res[0][169]=a09;
  if (res[0]!=0) res[0][170]=a08;
  if (res[0]!=0) res[0][171]=a09;
  if (res[0]!=0) res[0][172]=a00;
  if (res[0]!=0) res[0][173]=a09;
  if (res[0]!=0) res[0][174]=a01;
  if (res[0]!=0) res[0][175]=a09;
  if (res[0]!=0) res[0][176]=a02;
  if (res[0]!=0) res[0][177]=a09;
  if (res[0]!=0) res[0][178]=a03;
  if (res[0]!=0) res[0][179]=a09;
  if (res[0]!=0) res[0][180]=a04;
  if (res[0]!=0) res[0][181]=a09;
  if (res[0]!=0) res[0][182]=a05;
  if (res[0]!=0) res[0][183]=a09;
  if (res[0]!=0) res[0][184]=a06;
  if (res[0]!=0) res[0][185]=a09;
  if (res[0]!=0) res[0][186]=a07;
  if (res[0]!=0) res[0][187]=a09;
  if (res[0]!=0) res[0][188]=a08;
  a09=(a09+a09);
  if (res[0]!=0) res[0][189]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_hess_xu_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_hess_xu_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_hess_xu_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_hess_xu_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_hess_xu_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_hess_xu_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_hess_xu_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_hess_xu_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_e_hess_xu_p_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_e_hess_xu_p_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ocp_problem_cost_ext_cost_e_hess_xu_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_e_hess_xu_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_e_hess_xu_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_e_hess_xu_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_e_hess_xu_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_hess_xu_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_hess_xu_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
