/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_problem_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {461, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

/* ocp_problem_cost_ext_cost_e_fun:(i0[10],i1[0],i2[0],i3[0],i4[461])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a01=(a00*a01);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a03=(a02*a03);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a04=(a03*a04);
  a01=(a01+a04);
  a04=arg[0]? arg[0][3] : 0;
  a05=arg[4]? arg[4][3] : 0;
  a05=(a04*a05);
  a01=(a01+a05);
  a05=arg[0]? arg[0][4] : 0;
  a06=arg[4]? arg[4][4] : 0;
  a06=(a05*a06);
  a01=(a01+a06);
  a06=arg[0]? arg[0][5] : 0;
  a07=arg[4]? arg[4][5] : 0;
  a07=(a06*a07);
  a01=(a01+a07);
  a07=arg[0]? arg[0][6] : 0;
  a08=arg[4]? arg[4][6] : 0;
  a08=(a07*a08);
  a01=(a01+a08);
  a08=arg[0]? arg[0][7] : 0;
  a09=arg[4]? arg[4][7] : 0;
  a09=(a08*a09);
  a01=(a01+a09);
  a09=arg[0]? arg[0][8] : 0;
  a10=arg[4]? arg[4][8] : 0;
  a10=(a09*a10);
  a01=(a01+a10);
  a10=arg[0]? arg[0][9] : 0;
  a11=arg[4]? arg[4][9] : 0;
  a11=(a10*a11);
  a01=(a01+a11);
  a01=(a01*a00);
  a11=arg[4]? arg[4][14] : 0;
  a11=(a00*a11);
  a12=arg[4]? arg[4][15] : 0;
  a12=(a02*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][16] : 0;
  a12=(a03*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][17] : 0;
  a12=(a04*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][18] : 0;
  a12=(a05*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][19] : 0;
  a12=(a06*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][20] : 0;
  a12=(a07*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][21] : 0;
  a12=(a08*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][22] : 0;
  a12=(a09*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][23] : 0;
  a12=(a10*a12);
  a11=(a11+a12);
  a11=(a11*a02);
  a01=(a01+a11);
  a11=arg[4]? arg[4][28] : 0;
  a11=(a00*a11);
  a12=arg[4]? arg[4][29] : 0;
  a12=(a02*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][30] : 0;
  a12=(a03*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][31] : 0;
  a12=(a04*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][32] : 0;
  a12=(a05*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][33] : 0;
  a12=(a06*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][34] : 0;
  a12=(a07*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][35] : 0;
  a12=(a08*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][36] : 0;
  a12=(a09*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][37] : 0;
  a12=(a10*a12);
  a11=(a11+a12);
  a11=(a11*a03);
  a01=(a01+a11);
  a11=arg[4]? arg[4][42] : 0;
  a11=(a00*a11);
  a12=arg[4]? arg[4][43] : 0;
  a12=(a02*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][44] : 0;
  a12=(a03*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][45] : 0;
  a12=(a04*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][46] : 0;
  a12=(a05*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][47] : 0;
  a12=(a06*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][48] : 0;
  a12=(a07*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][49] : 0;
  a12=(a08*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][50] : 0;
  a12=(a09*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][51] : 0;
  a12=(a10*a12);
  a11=(a11+a12);
  a11=(a11*a04);
  a01=(a01+a11);
  a11=arg[4]? arg[4][56] : 0;
  a11=(a00*a11);
  a12=arg[4]? arg[4][57] : 0;
  a12=(a02*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][58] : 0;
  a12=(a03*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][59] : 0;
  a12=(a04*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][60] : 0;
  a12=(a05*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][61] : 0;
  a12=(a06*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][62] : 0;
  a12=(a07*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][63] : 0;
  a12=(a08*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][64] : 0;
  a12=(a09*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][65] : 0;
  a12=(a10*a12);
  a11=(a11+a12);
  a11=(a11*a05);
  a01=(a01+a11);
  a11=arg[4]? arg[4][70] : 0;
  a11=(a00*a11);
  a12=arg[4]? arg[4][71] : 0;
  a12=(a02*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][72] : 0;
  a12=(a03*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][73] : 0;
  a12=(a04*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][74] : 0;
  a12=(a05*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][75] : 0;
  a12=(a06*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][76] : 0;
  a12=(a07*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][77] : 0;
  a12=(a08*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][78] : 0;
  a12=(a09*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][79] : 0;
  a12=(a10*a12);
  a11=(a11+a12);
  a11=(a11*a06);
  a01=(a01+a11);
  a11=arg[4]? arg[4][84] : 0;
  a11=(a00*a11);
  a12=arg[4]? arg[4][85] : 0;
  a12=(a02*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][86] : 0;
  a12=(a03*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][87] : 0;
  a12=(a04*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][88] : 0;
  a12=(a05*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][89] : 0;
  a12=(a06*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][90] : 0;
  a12=(a07*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][91] : 0;
  a12=(a08*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][92] : 0;
  a12=(a09*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][93] : 0;
  a12=(a10*a12);
  a11=(a11+a12);
  a11=(a11*a07);
  a01=(a01+a11);
  a11=arg[4]? arg[4][98] : 0;
  a11=(a00*a11);
  a12=arg[4]? arg[4][99] : 0;
  a12=(a02*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][100] : 0;
  a12=(a03*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][101] : 0;
  a12=(a04*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][102] : 0;
  a12=(a05*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][103] : 0;
  a12=(a06*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][104] : 0;
  a12=(a07*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][105] : 0;
  a12=(a08*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][106] : 0;
  a12=(a09*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][107] : 0;
  a12=(a10*a12);
  a11=(a11+a12);
  a11=(a11*a08);
  a01=(a01+a11);
  a11=arg[4]? arg[4][112] : 0;
  a11=(a00*a11);
  a12=arg[4]? arg[4][113] : 0;
  a12=(a02*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][114] : 0;
  a12=(a03*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][115] : 0;
  a12=(a04*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][116] : 0;
  a12=(a05*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][117] : 0;
  a12=(a06*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][118] : 0;
  a12=(a07*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][119] : 0;
  a12=(a08*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][120] : 0;
  a12=(a09*a12);
  a11=(a11+a12);
  a12=arg[4]? arg[4][121] : 0;
  a12=(a10*a12);
  a11=(a11+a12);
  a11=(a11*a09);
  a01=(a01+a11);
  a11=arg[4]? arg[4][126] : 0;
  a00=(a00*a11);
  a11=arg[4]? arg[4][127] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[4]? arg[4][128] : 0;
  a03=(a03*a02);
  a00=(a00+a03);
  a03=arg[4]? arg[4][129] : 0;
  a04=(a04*a03);
  a00=(a00+a04);
  a04=arg[4]? arg[4][130] : 0;
  a05=(a05*a04);
  a00=(a00+a05);
  a05=arg[4]? arg[4][131] : 0;
  a06=(a06*a05);
  a00=(a00+a06);
  a06=arg[4]? arg[4][132] : 0;
  a07=(a07*a06);
  a00=(a00+a07);
  a07=arg[4]? arg[4][133] : 0;
  a08=(a08*a07);
  a00=(a00+a08);
  a08=arg[4]? arg[4][134] : 0;
  a09=(a09*a08);
  a00=(a00+a09);
  a09=arg[4]? arg[4][135] : 0;
  a09=(a10*a09);
  a00=(a00+a09);
  a00=(a00*a10);
  a01=(a01+a00);
  if (res[0]!=0) res[0][0]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_e_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ocp_problem_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
