/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_problem_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {461, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

/* ocp_problem_cost_ext_cost_e_fun_jac:(i0[10],i1[0],i2[0],i3[0],i4[461])->(o0,o1[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121;
  a000=arg[0]? arg[0][0] : 0;
  a001=arg[4]? arg[4][0] : 0;
  a002=(a000*a001);
  a003=arg[0]? arg[0][1] : 0;
  a004=arg[4]? arg[4][1] : 0;
  a005=(a003*a004);
  a002=(a002+a005);
  a005=arg[0]? arg[0][2] : 0;
  a006=arg[4]? arg[4][2] : 0;
  a007=(a005*a006);
  a002=(a002+a007);
  a007=arg[0]? arg[0][3] : 0;
  a008=arg[4]? arg[4][3] : 0;
  a009=(a007*a008);
  a002=(a002+a009);
  a009=arg[0]? arg[0][4] : 0;
  a010=arg[4]? arg[4][4] : 0;
  a011=(a009*a010);
  a002=(a002+a011);
  a011=arg[0]? arg[0][5] : 0;
  a012=arg[4]? arg[4][5] : 0;
  a013=(a011*a012);
  a002=(a002+a013);
  a013=arg[0]? arg[0][6] : 0;
  a014=arg[4]? arg[4][6] : 0;
  a015=(a013*a014);
  a002=(a002+a015);
  a015=arg[0]? arg[0][7] : 0;
  a016=arg[4]? arg[4][7] : 0;
  a017=(a015*a016);
  a002=(a002+a017);
  a017=arg[0]? arg[0][8] : 0;
  a018=arg[4]? arg[4][8] : 0;
  a019=(a017*a018);
  a002=(a002+a019);
  a019=arg[0]? arg[0][9] : 0;
  a020=arg[4]? arg[4][9] : 0;
  a021=(a019*a020);
  a002=(a002+a021);
  a021=(a002*a000);
  a022=arg[4]? arg[4][14] : 0;
  a023=(a000*a022);
  a024=arg[4]? arg[4][15] : 0;
  a025=(a003*a024);
  a023=(a023+a025);
  a025=arg[4]? arg[4][16] : 0;
  a026=(a005*a025);
  a023=(a023+a026);
  a026=arg[4]? arg[4][17] : 0;
  a027=(a007*a026);
  a023=(a023+a027);
  a027=arg[4]? arg[4][18] : 0;
  a028=(a009*a027);
  a023=(a023+a028);
  a028=arg[4]? arg[4][19] : 0;
  a029=(a011*a028);
  a023=(a023+a029);
  a029=arg[4]? arg[4][20] : 0;
  a030=(a013*a029);
  a023=(a023+a030);
  a030=arg[4]? arg[4][21] : 0;
  a031=(a015*a030);
  a023=(a023+a031);
  a031=arg[4]? arg[4][22] : 0;
  a032=(a017*a031);
  a023=(a023+a032);
  a032=arg[4]? arg[4][23] : 0;
  a033=(a019*a032);
  a023=(a023+a033);
  a033=(a023*a003);
  a021=(a021+a033);
  a033=arg[4]? arg[4][28] : 0;
  a034=(a000*a033);
  a035=arg[4]? arg[4][29] : 0;
  a036=(a003*a035);
  a034=(a034+a036);
  a036=arg[4]? arg[4][30] : 0;
  a037=(a005*a036);
  a034=(a034+a037);
  a037=arg[4]? arg[4][31] : 0;
  a038=(a007*a037);
  a034=(a034+a038);
  a038=arg[4]? arg[4][32] : 0;
  a039=(a009*a038);
  a034=(a034+a039);
  a039=arg[4]? arg[4][33] : 0;
  a040=(a011*a039);
  a034=(a034+a040);
  a040=arg[4]? arg[4][34] : 0;
  a041=(a013*a040);
  a034=(a034+a041);
  a041=arg[4]? arg[4][35] : 0;
  a042=(a015*a041);
  a034=(a034+a042);
  a042=arg[4]? arg[4][36] : 0;
  a043=(a017*a042);
  a034=(a034+a043);
  a043=arg[4]? arg[4][37] : 0;
  a044=(a019*a043);
  a034=(a034+a044);
  a044=(a034*a005);
  a021=(a021+a044);
  a044=arg[4]? arg[4][42] : 0;
  a045=(a000*a044);
  a046=arg[4]? arg[4][43] : 0;
  a047=(a003*a046);
  a045=(a045+a047);
  a047=arg[4]? arg[4][44] : 0;
  a048=(a005*a047);
  a045=(a045+a048);
  a048=arg[4]? arg[4][45] : 0;
  a049=(a007*a048);
  a045=(a045+a049);
  a049=arg[4]? arg[4][46] : 0;
  a050=(a009*a049);
  a045=(a045+a050);
  a050=arg[4]? arg[4][47] : 0;
  a051=(a011*a050);
  a045=(a045+a051);
  a051=arg[4]? arg[4][48] : 0;
  a052=(a013*a051);
  a045=(a045+a052);
  a052=arg[4]? arg[4][49] : 0;
  a053=(a015*a052);
  a045=(a045+a053);
  a053=arg[4]? arg[4][50] : 0;
  a054=(a017*a053);
  a045=(a045+a054);
  a054=arg[4]? arg[4][51] : 0;
  a055=(a019*a054);
  a045=(a045+a055);
  a055=(a045*a007);
  a021=(a021+a055);
  a055=arg[4]? arg[4][56] : 0;
  a056=(a000*a055);
  a057=arg[4]? arg[4][57] : 0;
  a058=(a003*a057);
  a056=(a056+a058);
  a058=arg[4]? arg[4][58] : 0;
  a059=(a005*a058);
  a056=(a056+a059);
  a059=arg[4]? arg[4][59] : 0;
  a060=(a007*a059);
  a056=(a056+a060);
  a060=arg[4]? arg[4][60] : 0;
  a061=(a009*a060);
  a056=(a056+a061);
  a061=arg[4]? arg[4][61] : 0;
  a062=(a011*a061);
  a056=(a056+a062);
  a062=arg[4]? arg[4][62] : 0;
  a063=(a013*a062);
  a056=(a056+a063);
  a063=arg[4]? arg[4][63] : 0;
  a064=(a015*a063);
  a056=(a056+a064);
  a064=arg[4]? arg[4][64] : 0;
  a065=(a017*a064);
  a056=(a056+a065);
  a065=arg[4]? arg[4][65] : 0;
  a066=(a019*a065);
  a056=(a056+a066);
  a066=(a056*a009);
  a021=(a021+a066);
  a066=arg[4]? arg[4][70] : 0;
  a067=(a000*a066);
  a068=arg[4]? arg[4][71] : 0;
  a069=(a003*a068);
  a067=(a067+a069);
  a069=arg[4]? arg[4][72] : 0;
  a070=(a005*a069);
  a067=(a067+a070);
  a070=arg[4]? arg[4][73] : 0;
  a071=(a007*a070);
  a067=(a067+a071);
  a071=arg[4]? arg[4][74] : 0;
  a072=(a009*a071);
  a067=(a067+a072);
  a072=arg[4]? arg[4][75] : 0;
  a073=(a011*a072);
  a067=(a067+a073);
  a073=arg[4]? arg[4][76] : 0;
  a074=(a013*a073);
  a067=(a067+a074);
  a074=arg[4]? arg[4][77] : 0;
  a075=(a015*a074);
  a067=(a067+a075);
  a075=arg[4]? arg[4][78] : 0;
  a076=(a017*a075);
  a067=(a067+a076);
  a076=arg[4]? arg[4][79] : 0;
  a077=(a019*a076);
  a067=(a067+a077);
  a077=(a067*a011);
  a021=(a021+a077);
  a077=arg[4]? arg[4][84] : 0;
  a078=(a000*a077);
  a079=arg[4]? arg[4][85] : 0;
  a080=(a003*a079);
  a078=(a078+a080);
  a080=arg[4]? arg[4][86] : 0;
  a081=(a005*a080);
  a078=(a078+a081);
  a081=arg[4]? arg[4][87] : 0;
  a082=(a007*a081);
  a078=(a078+a082);
  a082=arg[4]? arg[4][88] : 0;
  a083=(a009*a082);
  a078=(a078+a083);
  a083=arg[4]? arg[4][89] : 0;
  a084=(a011*a083);
  a078=(a078+a084);
  a084=arg[4]? arg[4][90] : 0;
  a085=(a013*a084);
  a078=(a078+a085);
  a085=arg[4]? arg[4][91] : 0;
  a086=(a015*a085);
  a078=(a078+a086);
  a086=arg[4]? arg[4][92] : 0;
  a087=(a017*a086);
  a078=(a078+a087);
  a087=arg[4]? arg[4][93] : 0;
  a088=(a019*a087);
  a078=(a078+a088);
  a088=(a078*a013);
  a021=(a021+a088);
  a088=arg[4]? arg[4][98] : 0;
  a089=(a000*a088);
  a090=arg[4]? arg[4][99] : 0;
  a091=(a003*a090);
  a089=(a089+a091);
  a091=arg[4]? arg[4][100] : 0;
  a092=(a005*a091);
  a089=(a089+a092);
  a092=arg[4]? arg[4][101] : 0;
  a093=(a007*a092);
  a089=(a089+a093);
  a093=arg[4]? arg[4][102] : 0;
  a094=(a009*a093);
  a089=(a089+a094);
  a094=arg[4]? arg[4][103] : 0;
  a095=(a011*a094);
  a089=(a089+a095);
  a095=arg[4]? arg[4][104] : 0;
  a096=(a013*a095);
  a089=(a089+a096);
  a096=arg[4]? arg[4][105] : 0;
  a097=(a015*a096);
  a089=(a089+a097);
  a097=arg[4]? arg[4][106] : 0;
  a098=(a017*a097);
  a089=(a089+a098);
  a098=arg[4]? arg[4][107] : 0;
  a099=(a019*a098);
  a089=(a089+a099);
  a099=(a089*a015);
  a021=(a021+a099);
  a099=arg[4]? arg[4][112] : 0;
  a100=(a000*a099);
  a101=arg[4]? arg[4][113] : 0;
  a102=(a003*a101);
  a100=(a100+a102);
  a102=arg[4]? arg[4][114] : 0;
  a103=(a005*a102);
  a100=(a100+a103);
  a103=arg[4]? arg[4][115] : 0;
  a104=(a007*a103);
  a100=(a100+a104);
  a104=arg[4]? arg[4][116] : 0;
  a105=(a009*a104);
  a100=(a100+a105);
  a105=arg[4]? arg[4][117] : 0;
  a106=(a011*a105);
  a100=(a100+a106);
  a106=arg[4]? arg[4][118] : 0;
  a107=(a013*a106);
  a100=(a100+a107);
  a107=arg[4]? arg[4][119] : 0;
  a108=(a015*a107);
  a100=(a100+a108);
  a108=arg[4]? arg[4][120] : 0;
  a109=(a017*a108);
  a100=(a100+a109);
  a109=arg[4]? arg[4][121] : 0;
  a110=(a019*a109);
  a100=(a100+a110);
  a110=(a100*a017);
  a021=(a021+a110);
  a110=arg[4]? arg[4][126] : 0;
  a111=(a000*a110);
  a112=arg[4]? arg[4][127] : 0;
  a113=(a003*a112);
  a111=(a111+a113);
  a113=arg[4]? arg[4][128] : 0;
  a114=(a005*a113);
  a111=(a111+a114);
  a114=arg[4]? arg[4][129] : 0;
  a115=(a007*a114);
  a111=(a111+a115);
  a115=arg[4]? arg[4][130] : 0;
  a116=(a009*a115);
  a111=(a111+a116);
  a116=arg[4]? arg[4][131] : 0;
  a117=(a011*a116);
  a111=(a111+a117);
  a117=arg[4]? arg[4][132] : 0;
  a118=(a013*a117);
  a111=(a111+a118);
  a118=arg[4]? arg[4][133] : 0;
  a119=(a015*a118);
  a111=(a111+a119);
  a119=arg[4]? arg[4][134] : 0;
  a120=(a017*a119);
  a111=(a111+a120);
  a120=arg[4]? arg[4][135] : 0;
  a121=(a019*a120);
  a111=(a111+a121);
  a121=(a111*a019);
  a021=(a021+a121);
  if (res[0]!=0) res[0][0]=a021;
  a110=(a110*a019);
  a099=(a099*a017);
  a110=(a110+a099);
  a088=(a088*a015);
  a110=(a110+a088);
  a077=(a077*a013);
  a110=(a110+a077);
  a066=(a066*a011);
  a110=(a110+a066);
  a055=(a055*a009);
  a110=(a110+a055);
  a044=(a044*a007);
  a110=(a110+a044);
  a033=(a033*a005);
  a110=(a110+a033);
  a022=(a022*a003);
  a110=(a110+a022);
  a110=(a110+a002);
  a001=(a001*a000);
  a110=(a110+a001);
  if (res[1]!=0) res[1][0]=a110;
  a112=(a112*a019);
  a101=(a101*a017);
  a112=(a112+a101);
  a090=(a090*a015);
  a112=(a112+a090);
  a079=(a079*a013);
  a112=(a112+a079);
  a068=(a068*a011);
  a112=(a112+a068);
  a057=(a057*a009);
  a112=(a112+a057);
  a046=(a046*a007);
  a112=(a112+a046);
  a035=(a035*a005);
  a112=(a112+a035);
  a112=(a112+a023);
  a024=(a024*a003);
  a112=(a112+a024);
  a004=(a004*a000);
  a112=(a112+a004);
  if (res[1]!=0) res[1][1]=a112;
  a113=(a113*a019);
  a102=(a102*a017);
  a113=(a113+a102);
  a091=(a091*a015);
  a113=(a113+a091);
  a080=(a080*a013);
  a113=(a113+a080);
  a069=(a069*a011);
  a113=(a113+a069);
  a058=(a058*a009);
  a113=(a113+a058);
  a047=(a047*a007);
  a113=(a113+a047);
  a113=(a113+a034);
  a036=(a036*a005);
  a113=(a113+a036);
  a025=(a025*a003);
  a113=(a113+a025);
  a006=(a006*a000);
  a113=(a113+a006);
  if (res[1]!=0) res[1][2]=a113;
  a114=(a114*a019);
  a103=(a103*a017);
  a114=(a114+a103);
  a092=(a092*a015);
  a114=(a114+a092);
  a081=(a081*a013);
  a114=(a114+a081);
  a070=(a070*a011);
  a114=(a114+a070);
  a059=(a059*a009);
  a114=(a114+a059);
  a114=(a114+a045);
  a048=(a048*a007);
  a114=(a114+a048);
  a037=(a037*a005);
  a114=(a114+a037);
  a026=(a026*a003);
  a114=(a114+a026);
  a008=(a008*a000);
  a114=(a114+a008);
  if (res[1]!=0) res[1][3]=a114;
  a115=(a115*a019);
  a104=(a104*a017);
  a115=(a115+a104);
  a093=(a093*a015);
  a115=(a115+a093);
  a082=(a082*a013);
  a115=(a115+a082);
  a071=(a071*a011);
  a115=(a115+a071);
  a115=(a115+a056);
  a060=(a060*a009);
  a115=(a115+a060);
  a049=(a049*a007);
  a115=(a115+a049);
  a038=(a038*a005);
  a115=(a115+a038);
  a027=(a027*a003);
  a115=(a115+a027);
  a010=(a010*a000);
  a115=(a115+a010);
  if (res[1]!=0) res[1][4]=a115;
  a116=(a116*a019);
  a105=(a105*a017);
  a116=(a116+a105);
  a094=(a094*a015);
  a116=(a116+a094);
  a083=(a083*a013);
  a116=(a116+a083);
  a116=(a116+a067);
  a072=(a072*a011);
  a116=(a116+a072);
  a061=(a061*a009);
  a116=(a116+a061);
  a050=(a050*a007);
  a116=(a116+a050);
  a039=(a039*a005);
  a116=(a116+a039);
  a028=(a028*a003);
  a116=(a116+a028);
  a012=(a012*a000);
  a116=(a116+a012);
  if (res[1]!=0) res[1][5]=a116;
  a117=(a117*a019);
  a106=(a106*a017);
  a117=(a117+a106);
  a095=(a095*a015);
  a117=(a117+a095);
  a117=(a117+a078);
  a084=(a084*a013);
  a117=(a117+a084);
  a073=(a073*a011);
  a117=(a117+a073);
  a062=(a062*a009);
  a117=(a117+a062);
  a051=(a051*a007);
  a117=(a117+a051);
  a040=(a040*a005);
  a117=(a117+a040);
  a029=(a029*a003);
  a117=(a117+a029);
  a014=(a014*a000);
  a117=(a117+a014);
  if (res[1]!=0) res[1][6]=a117;
  a118=(a118*a019);
  a107=(a107*a017);
  a118=(a118+a107);
  a118=(a118+a089);
  a096=(a096*a015);
  a118=(a118+a096);
  a085=(a085*a013);
  a118=(a118+a085);
  a074=(a074*a011);
  a118=(a118+a074);
  a063=(a063*a009);
  a118=(a118+a063);
  a052=(a052*a007);
  a118=(a118+a052);
  a041=(a041*a005);
  a118=(a118+a041);
  a030=(a030*a003);
  a118=(a118+a030);
  a016=(a016*a000);
  a118=(a118+a016);
  if (res[1]!=0) res[1][7]=a118;
  a119=(a119*a019);
  a119=(a119+a100);
  a108=(a108*a017);
  a119=(a119+a108);
  a097=(a097*a015);
  a119=(a119+a097);
  a086=(a086*a013);
  a119=(a119+a086);
  a075=(a075*a011);
  a119=(a119+a075);
  a064=(a064*a009);
  a119=(a119+a064);
  a053=(a053*a007);
  a119=(a119+a053);
  a042=(a042*a005);
  a119=(a119+a042);
  a031=(a031*a003);
  a119=(a119+a031);
  a018=(a018*a000);
  a119=(a119+a018);
  if (res[1]!=0) res[1][8]=a119;
  a120=(a120*a019);
  a111=(a111+a120);
  a109=(a109*a017);
  a111=(a111+a109);
  a098=(a098*a015);
  a111=(a111+a098);
  a087=(a087*a013);
  a111=(a111+a087);
  a076=(a076*a011);
  a111=(a111+a076);
  a065=(a065*a009);
  a111=(a111+a065);
  a054=(a054*a007);
  a111=(a111+a054);
  a043=(a043*a005);
  a111=(a111+a043);
  a032=(a032*a003);
  a111=(a111+a032);
  a020=(a020*a000);
  a111=(a111+a020);
  if (res[1]!=0) res[1][9]=a111;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_e_fun_jac_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ocp_problem_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
