/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_problem_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {461, 1, 1};

/* ocp_problem_dyn_disc_phi_fun:(i0[10],i1[4],i2[0],i3[461])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42;
  a00=arg[0]? arg[0][0] : 0;
  a01=8.3333333333333332e-03;
  a02=arg[0]? arg[0][7] : 0;
  a03=2.;
  a04=2.5000000000000001e-02;
  a05=arg[0]? arg[0][3] : 0;
  a06=arg[0]? arg[0][5] : 0;
  a07=(a05*a06);
  a08=arg[0]? arg[0][4] : 0;
  a09=arg[0]? arg[0][6] : 0;
  a10=(a08*a09);
  a07=(a07+a10);
  a07=(a03*a07);
  a10=arg[1]? arg[1][0] : 0;
  a07=(a07*a10);
  a11=(a04*a07);
  a11=(a02+a11);
  a11=(a03*a11);
  a11=(a02+a11);
  a12=-5.0000000000000000e-01;
  a13=arg[1]? arg[1][1] : 0;
  a14=(a13*a08);
  a15=arg[1]? arg[1][2] : 0;
  a16=(a15*a06);
  a14=(a14+a16);
  a16=arg[1]? arg[1][3] : 0;
  a17=(a16*a09);
  a14=(a14+a17);
  a14=(a12*a14);
  a17=(a04*a14);
  a17=(a05+a17);
  a18=5.0000000000000000e-01;
  a19=(a15*a05);
  a20=(a16*a08);
  a19=(a19-a20);
  a20=(a13*a09);
  a19=(a19+a20);
  a19=(a18*a19);
  a20=(a04*a19);
  a20=(a06+a20);
  a21=(a17*a20);
  a22=(a13*a05);
  a23=(a16*a06);
  a22=(a22+a23);
  a23=(a15*a09);
  a22=(a22-a23);
  a22=(a18*a22);
  a23=(a04*a22);
  a23=(a08+a23);
  a24=(a16*a05);
  a25=(a15*a08);
  a24=(a24+a25);
  a25=(a13*a06);
  a24=(a24-a25);
  a24=(a18*a24);
  a25=(a04*a24);
  a25=(a09+a25);
  a26=(a23*a25);
  a21=(a21+a26);
  a21=(a03*a21);
  a21=(a21*a10);
  a26=(a04*a21);
  a26=(a02+a26);
  a26=(a03*a26);
  a11=(a11+a26);
  a26=5.0000000000000003e-02;
  a27=(a13*a23);
  a28=(a15*a20);
  a27=(a27+a28);
  a28=(a16*a25);
  a27=(a27+a28);
  a27=(a12*a27);
  a28=(a04*a27);
  a28=(a05+a28);
  a29=(a15*a17);
  a30=(a16*a23);
  a29=(a29-a30);
  a30=(a13*a25);
  a29=(a29+a30);
  a30=(a18*a29);
  a30=(a04*a30);
  a30=(a06+a30);
  a31=(a28*a30);
  a32=(a13*a17);
  a33=(a16*a20);
  a32=(a32+a33);
  a33=(a15*a25);
  a32=(a32-a33);
  a33=(a18*a32);
  a33=(a04*a33);
  a33=(a08+a33);
  a34=(a16*a17);
  a35=(a15*a23);
  a34=(a34+a35);
  a35=(a13*a20);
  a34=(a34-a35);
  a35=(a18*a34);
  a35=(a04*a35);
  a35=(a09+a35);
  a36=(a33*a35);
  a31=(a31+a36);
  a31=(a03*a31);
  a31=(a31*a10);
  a36=(a26*a31);
  a36=(a02+a36);
  a11=(a11+a36);
  a11=(a01*a11);
  a00=(a00+a11);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a11=arg[0]? arg[0][8] : 0;
  a36=(a06*a09);
  a37=(a05*a08);
  a36=(a36-a37);
  a36=(a03*a36);
  a36=(a36*a10);
  a37=(a04*a36);
  a37=(a11+a37);
  a37=(a03*a37);
  a37=(a11+a37);
  a38=(a20*a25);
  a39=(a17*a23);
  a38=(a38-a39);
  a38=(a03*a38);
  a38=(a38*a10);
  a39=(a04*a38);
  a39=(a11+a39);
  a39=(a03*a39);
  a37=(a37+a39);
  a39=(a30*a35);
  a40=(a28*a33);
  a39=(a39-a40);
  a39=(a03*a39);
  a39=(a39*a10);
  a40=(a26*a39);
  a40=(a11+a40);
  a37=(a37+a40);
  a37=(a01*a37);
  a00=(a00+a37);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a37=arg[0]? arg[0][9] : 0;
  a40=casadi_sq(a05);
  a41=casadi_sq(a08);
  a40=(a40-a41);
  a41=casadi_sq(a06);
  a40=(a40-a41);
  a41=casadi_sq(a09);
  a40=(a40+a41);
  a40=(a40*a10);
  a41=9.8100000000000005e+00;
  a40=(a40-a41);
  a42=(a04*a40);
  a42=(a37+a42);
  a42=(a03*a42);
  a42=(a37+a42);
  a17=casadi_sq(a17);
  a23=casadi_sq(a23);
  a17=(a17-a23);
  a20=casadi_sq(a20);
  a17=(a17-a20);
  a25=casadi_sq(a25);
  a17=(a17+a25);
  a17=(a17*a10);
  a17=(a17-a41);
  a04=(a04*a17);
  a04=(a37+a04);
  a04=(a03*a04);
  a42=(a42+a04);
  a04=casadi_sq(a28);
  a25=casadi_sq(a33);
  a04=(a04-a25);
  a25=casadi_sq(a30);
  a04=(a04-a25);
  a25=casadi_sq(a35);
  a04=(a04+a25);
  a04=(a04*a10);
  a04=(a04-a41);
  a25=(a26*a04);
  a25=(a37+a25);
  a42=(a42+a25);
  a42=(a01*a42);
  a00=(a00+a42);
  if (res[0]!=0) res[0][2]=a00;
  a27=(a03*a27);
  a14=(a14+a27);
  a27=(a13*a33);
  a00=(a15*a30);
  a27=(a27+a00);
  a00=(a16*a35);
  a27=(a27+a00);
  a27=(a12*a27);
  a00=(a03*a27);
  a14=(a14+a00);
  a00=(a13*a28);
  a42=(a16*a30);
  a00=(a00+a42);
  a42=(a15*a35);
  a00=(a00-a42);
  a42=(a18*a00);
  a42=(a26*a42);
  a42=(a08+a42);
  a25=(a13*a42);
  a20=(a15*a28);
  a23=(a16*a33);
  a20=(a20-a23);
  a35=(a13*a35);
  a20=(a20+a35);
  a35=(a18*a20);
  a35=(a26*a35);
  a35=(a06+a35);
  a23=(a15*a35);
  a25=(a25+a23);
  a28=(a16*a28);
  a33=(a15*a33);
  a28=(a28+a33);
  a30=(a13*a30);
  a28=(a28-a30);
  a30=(a18*a28);
  a30=(a26*a30);
  a30=(a09+a30);
  a33=(a16*a30);
  a25=(a25+a33);
  a12=(a12*a25);
  a14=(a14+a12);
  a14=(a01*a14);
  a14=(a05+a14);
  a12=casadi_sq(a14);
  a22=(a22+a32);
  a22=(a22+a00);
  a26=(a26*a27);
  a05=(a05+a26);
  a26=(a13*a05);
  a27=(a16*a35);
  a26=(a26+a27);
  a27=(a15*a30);
  a26=(a26-a27);
  a26=(a18*a26);
  a22=(a22+a26);
  a22=(a01*a22);
  a08=(a08+a22);
  a22=casadi_sq(a08);
  a12=(a12+a22);
  a19=(a19+a29);
  a19=(a19+a20);
  a20=(a15*a05);
  a29=(a16*a42);
  a20=(a20-a29);
  a29=(a13*a30);
  a20=(a20+a29);
  a20=(a18*a20);
  a19=(a19+a20);
  a19=(a01*a19);
  a06=(a06+a19);
  a19=casadi_sq(a06);
  a12=(a12+a19);
  a24=(a24+a34);
  a24=(a24+a28);
  a16=(a16*a05);
  a15=(a15*a42);
  a16=(a16+a15);
  a13=(a13*a35);
  a16=(a16-a13);
  a18=(a18*a16);
  a24=(a24+a18);
  a24=(a01*a24);
  a09=(a09+a24);
  a24=casadi_sq(a09);
  a12=(a12+a24);
  a24=9.9999999999999998e-13;
  a12=(a12+a24);
  a12=sqrt(a12);
  a14=(a14/a12);
  if (res[0]!=0) res[0][3]=a14;
  a08=(a08/a12);
  if (res[0]!=0) res[0][4]=a08;
  a06=(a06/a12);
  if (res[0]!=0) res[0][5]=a06;
  a09=(a09/a12);
  if (res[0]!=0) res[0][6]=a09;
  a21=(a03*a21);
  a07=(a07+a21);
  a31=(a03*a31);
  a07=(a07+a31);
  a31=(a05*a35);
  a21=(a42*a30);
  a31=(a31+a21);
  a31=(a03*a31);
  a31=(a31*a10);
  a07=(a07+a31);
  a07=(a01*a07);
  a02=(a02+a07);
  if (res[0]!=0) res[0][7]=a02;
  a38=(a03*a38);
  a36=(a36+a38);
  a39=(a03*a39);
  a36=(a36+a39);
  a39=(a35*a30);
  a38=(a05*a42);
  a39=(a39-a38);
  a39=(a03*a39);
  a39=(a39*a10);
  a36=(a36+a39);
  a36=(a01*a36);
  a11=(a11+a36);
  if (res[0]!=0) res[0][8]=a11;
  a17=(a03*a17);
  a40=(a40+a17);
  a03=(a03*a04);
  a40=(a40+a03);
  a05=casadi_sq(a05);
  a42=casadi_sq(a42);
  a05=(a05-a42);
  a35=casadi_sq(a35);
  a05=(a05-a35);
  a30=casadi_sq(a30);
  a05=(a05+a30);
  a05=(a05*a10);
  a05=(a05-a41);
  a40=(a40+a05);
  a01=(a01*a40);
  a37=(a37+a01);
  if (res[0]!=0) res[0][9]=a37;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_problem_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_problem_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_dyn_disc_phi_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ocp_problem_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_problem_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
