/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_problem_p_global_precompute_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {196, 1, 1};
static const casadi_int casadi_s1[3] = {461, 1, 1};

/* ocp_problem_p_global_precompute_fun:(i0[196])->(o0[461]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133, a134, a135, a136, a137, a138, a139, a140, a141, a142, a143;
  casadi_real a144, a145, a146, a147, a148, a149, a150, a151, a152, a153, a154, a155;
  casadi_real a156, a157, a158, a159, a160, a161, a162, a163, a164, a165, a166, a167;
  casadi_real a168, a169, a170, a171, a172, a173, a174, a175, a176, a177, a178, a179;
  casadi_real a180, a181, a182, a183, a184, a185, a186, a187, a188, a189, a190, a191;
  casadi_real a192, a193, a194, a195;
  a000=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a000;
  a001=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a001;
  a002=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a002;
  a003=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a003;
  a004=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a004;
  a005=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a005;
  a006=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a006;
  a007=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a007;
  a008=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][8]=a008;
  a009=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a009;
  a010=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a010;
  a011=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a011;
  a012=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a012;
  a013=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a013;
  a014=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a014;
  a015=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a015;
  a016=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a016;
  a017=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a017;
  a018=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a018;
  a019=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a019;
  a020=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a020;
  a021=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][21]=a021;
  a022=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][22]=a022;
  a023=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][23]=a023;
  a024=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][24]=a024;
  a025=arg[0]? arg[0][25] : 0;
  if (res[0]!=0) res[0][25]=a025;
  a026=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][26]=a026;
  a027=arg[0]? arg[0][27] : 0;
  if (res[0]!=0) res[0][27]=a027;
  a028=arg[0]? arg[0][28] : 0;
  if (res[0]!=0) res[0][28]=a028;
  a029=arg[0]? arg[0][29] : 0;
  if (res[0]!=0) res[0][29]=a029;
  a030=arg[0]? arg[0][30] : 0;
  if (res[0]!=0) res[0][30]=a030;
  a031=arg[0]? arg[0][31] : 0;
  if (res[0]!=0) res[0][31]=a031;
  a032=arg[0]? arg[0][32] : 0;
  if (res[0]!=0) res[0][32]=a032;
  a033=arg[0]? arg[0][33] : 0;
  if (res[0]!=0) res[0][33]=a033;
  a034=arg[0]? arg[0][34] : 0;
  if (res[0]!=0) res[0][34]=a034;
  a035=arg[0]? arg[0][35] : 0;
  if (res[0]!=0) res[0][35]=a035;
  a036=arg[0]? arg[0][36] : 0;
  if (res[0]!=0) res[0][36]=a036;
  a037=arg[0]? arg[0][37] : 0;
  if (res[0]!=0) res[0][37]=a037;
  a038=arg[0]? arg[0][38] : 0;
  if (res[0]!=0) res[0][38]=a038;
  a039=arg[0]? arg[0][39] : 0;
  if (res[0]!=0) res[0][39]=a039;
  a040=arg[0]? arg[0][40] : 0;
  if (res[0]!=0) res[0][40]=a040;
  a041=arg[0]? arg[0][41] : 0;
  if (res[0]!=0) res[0][41]=a041;
  a042=arg[0]? arg[0][42] : 0;
  if (res[0]!=0) res[0][42]=a042;
  a043=arg[0]? arg[0][43] : 0;
  if (res[0]!=0) res[0][43]=a043;
  a044=arg[0]? arg[0][44] : 0;
  if (res[0]!=0) res[0][44]=a044;
  a045=arg[0]? arg[0][45] : 0;
  if (res[0]!=0) res[0][45]=a045;
  a046=arg[0]? arg[0][46] : 0;
  if (res[0]!=0) res[0][46]=a046;
  a047=arg[0]? arg[0][47] : 0;
  if (res[0]!=0) res[0][47]=a047;
  a048=arg[0]? arg[0][48] : 0;
  if (res[0]!=0) res[0][48]=a048;
  a049=arg[0]? arg[0][49] : 0;
  if (res[0]!=0) res[0][49]=a049;
  a050=arg[0]? arg[0][50] : 0;
  if (res[0]!=0) res[0][50]=a050;
  a051=arg[0]? arg[0][51] : 0;
  if (res[0]!=0) res[0][51]=a051;
  a052=arg[0]? arg[0][52] : 0;
  if (res[0]!=0) res[0][52]=a052;
  a053=arg[0]? arg[0][53] : 0;
  if (res[0]!=0) res[0][53]=a053;
  a054=arg[0]? arg[0][54] : 0;
  if (res[0]!=0) res[0][54]=a054;
  a055=arg[0]? arg[0][55] : 0;
  if (res[0]!=0) res[0][55]=a055;
  a056=arg[0]? arg[0][56] : 0;
  if (res[0]!=0) res[0][56]=a056;
  a057=arg[0]? arg[0][57] : 0;
  if (res[0]!=0) res[0][57]=a057;
  a058=arg[0]? arg[0][58] : 0;
  if (res[0]!=0) res[0][58]=a058;
  a059=arg[0]? arg[0][59] : 0;
  if (res[0]!=0) res[0][59]=a059;
  a060=arg[0]? arg[0][60] : 0;
  if (res[0]!=0) res[0][60]=a060;
  a061=arg[0]? arg[0][61] : 0;
  if (res[0]!=0) res[0][61]=a061;
  a062=arg[0]? arg[0][62] : 0;
  if (res[0]!=0) res[0][62]=a062;
  a063=arg[0]? arg[0][63] : 0;
  if (res[0]!=0) res[0][63]=a063;
  a064=arg[0]? arg[0][64] : 0;
  if (res[0]!=0) res[0][64]=a064;
  a065=arg[0]? arg[0][65] : 0;
  if (res[0]!=0) res[0][65]=a065;
  a066=arg[0]? arg[0][66] : 0;
  if (res[0]!=0) res[0][66]=a066;
  a067=arg[0]? arg[0][67] : 0;
  if (res[0]!=0) res[0][67]=a067;
  a068=arg[0]? arg[0][68] : 0;
  if (res[0]!=0) res[0][68]=a068;
  a069=arg[0]? arg[0][69] : 0;
  if (res[0]!=0) res[0][69]=a069;
  a070=arg[0]? arg[0][70] : 0;
  if (res[0]!=0) res[0][70]=a070;
  a071=arg[0]? arg[0][71] : 0;
  if (res[0]!=0) res[0][71]=a071;
  a072=arg[0]? arg[0][72] : 0;
  if (res[0]!=0) res[0][72]=a072;
  a073=arg[0]? arg[0][73] : 0;
  if (res[0]!=0) res[0][73]=a073;
  a074=arg[0]? arg[0][74] : 0;
  if (res[0]!=0) res[0][74]=a074;
  a075=arg[0]? arg[0][75] : 0;
  if (res[0]!=0) res[0][75]=a075;
  a076=arg[0]? arg[0][76] : 0;
  if (res[0]!=0) res[0][76]=a076;
  a077=arg[0]? arg[0][77] : 0;
  if (res[0]!=0) res[0][77]=a077;
  a078=arg[0]? arg[0][78] : 0;
  if (res[0]!=0) res[0][78]=a078;
  a079=arg[0]? arg[0][79] : 0;
  if (res[0]!=0) res[0][79]=a079;
  a080=arg[0]? arg[0][80] : 0;
  if (res[0]!=0) res[0][80]=a080;
  a081=arg[0]? arg[0][81] : 0;
  if (res[0]!=0) res[0][81]=a081;
  a082=arg[0]? arg[0][82] : 0;
  if (res[0]!=0) res[0][82]=a082;
  a083=arg[0]? arg[0][83] : 0;
  if (res[0]!=0) res[0][83]=a083;
  a084=arg[0]? arg[0][84] : 0;
  if (res[0]!=0) res[0][84]=a084;
  a085=arg[0]? arg[0][85] : 0;
  if (res[0]!=0) res[0][85]=a085;
  a086=arg[0]? arg[0][86] : 0;
  if (res[0]!=0) res[0][86]=a086;
  a087=arg[0]? arg[0][87] : 0;
  if (res[0]!=0) res[0][87]=a087;
  a088=arg[0]? arg[0][88] : 0;
  if (res[0]!=0) res[0][88]=a088;
  a089=arg[0]? arg[0][89] : 0;
  if (res[0]!=0) res[0][89]=a089;
  a090=arg[0]? arg[0][90] : 0;
  if (res[0]!=0) res[0][90]=a090;
  a091=arg[0]? arg[0][91] : 0;
  if (res[0]!=0) res[0][91]=a091;
  a092=arg[0]? arg[0][92] : 0;
  if (res[0]!=0) res[0][92]=a092;
  a093=arg[0]? arg[0][93] : 0;
  if (res[0]!=0) res[0][93]=a093;
  a094=arg[0]? arg[0][94] : 0;
  if (res[0]!=0) res[0][94]=a094;
  a095=arg[0]? arg[0][95] : 0;
  if (res[0]!=0) res[0][95]=a095;
  a096=arg[0]? arg[0][96] : 0;
  if (res[0]!=0) res[0][96]=a096;
  a097=arg[0]? arg[0][97] : 0;
  if (res[0]!=0) res[0][97]=a097;
  a098=arg[0]? arg[0][98] : 0;
  if (res[0]!=0) res[0][98]=a098;
  a099=arg[0]? arg[0][99] : 0;
  if (res[0]!=0) res[0][99]=a099;
  a100=arg[0]? arg[0][100] : 0;
  if (res[0]!=0) res[0][100]=a100;
  a101=arg[0]? arg[0][101] : 0;
  if (res[0]!=0) res[0][101]=a101;
  a102=arg[0]? arg[0][102] : 0;
  if (res[0]!=0) res[0][102]=a102;
  a103=arg[0]? arg[0][103] : 0;
  if (res[0]!=0) res[0][103]=a103;
  a104=arg[0]? arg[0][104] : 0;
  if (res[0]!=0) res[0][104]=a104;
  a105=arg[0]? arg[0][105] : 0;
  if (res[0]!=0) res[0][105]=a105;
  a106=arg[0]? arg[0][106] : 0;
  if (res[0]!=0) res[0][106]=a106;
  a107=arg[0]? arg[0][107] : 0;
  if (res[0]!=0) res[0][107]=a107;
  a108=arg[0]? arg[0][108] : 0;
  if (res[0]!=0) res[0][108]=a108;
  a109=arg[0]? arg[0][109] : 0;
  if (res[0]!=0) res[0][109]=a109;
  a110=arg[0]? arg[0][110] : 0;
  if (res[0]!=0) res[0][110]=a110;
  a111=arg[0]? arg[0][111] : 0;
  if (res[0]!=0) res[0][111]=a111;
  a112=arg[0]? arg[0][112] : 0;
  if (res[0]!=0) res[0][112]=a112;
  a113=arg[0]? arg[0][113] : 0;
  if (res[0]!=0) res[0][113]=a113;
  a114=arg[0]? arg[0][114] : 0;
  if (res[0]!=0) res[0][114]=a114;
  a115=arg[0]? arg[0][115] : 0;
  if (res[0]!=0) res[0][115]=a115;
  a116=arg[0]? arg[0][116] : 0;
  if (res[0]!=0) res[0][116]=a116;
  a117=arg[0]? arg[0][117] : 0;
  if (res[0]!=0) res[0][117]=a117;
  a118=arg[0]? arg[0][118] : 0;
  if (res[0]!=0) res[0][118]=a118;
  a119=arg[0]? arg[0][119] : 0;
  if (res[0]!=0) res[0][119]=a119;
  a120=arg[0]? arg[0][120] : 0;
  if (res[0]!=0) res[0][120]=a120;
  a121=arg[0]? arg[0][121] : 0;
  if (res[0]!=0) res[0][121]=a121;
  a122=arg[0]? arg[0][122] : 0;
  if (res[0]!=0) res[0][122]=a122;
  a123=arg[0]? arg[0][123] : 0;
  if (res[0]!=0) res[0][123]=a123;
  a124=arg[0]? arg[0][124] : 0;
  if (res[0]!=0) res[0][124]=a124;
  a125=arg[0]? arg[0][125] : 0;
  if (res[0]!=0) res[0][125]=a125;
  a126=arg[0]? arg[0][126] : 0;
  if (res[0]!=0) res[0][126]=a126;
  a127=arg[0]? arg[0][127] : 0;
  if (res[0]!=0) res[0][127]=a127;
  a128=arg[0]? arg[0][128] : 0;
  if (res[0]!=0) res[0][128]=a128;
  a129=arg[0]? arg[0][129] : 0;
  if (res[0]!=0) res[0][129]=a129;
  a130=arg[0]? arg[0][130] : 0;
  if (res[0]!=0) res[0][130]=a130;
  a131=arg[0]? arg[0][131] : 0;
  if (res[0]!=0) res[0][131]=a131;
  a132=arg[0]? arg[0][132] : 0;
  if (res[0]!=0) res[0][132]=a132;
  a133=arg[0]? arg[0][133] : 0;
  if (res[0]!=0) res[0][133]=a133;
  a134=arg[0]? arg[0][134] : 0;
  if (res[0]!=0) res[0][134]=a134;
  a135=arg[0]? arg[0][135] : 0;
  if (res[0]!=0) res[0][135]=a135;
  a136=arg[0]? arg[0][136] : 0;
  if (res[0]!=0) res[0][136]=a136;
  a137=arg[0]? arg[0][137] : 0;
  if (res[0]!=0) res[0][137]=a137;
  a138=arg[0]? arg[0][138] : 0;
  if (res[0]!=0) res[0][138]=a138;
  a139=arg[0]? arg[0][139] : 0;
  if (res[0]!=0) res[0][139]=a139;
  a140=arg[0]? arg[0][140] : 0;
  if (res[0]!=0) res[0][140]=a140;
  a141=arg[0]? arg[0][141] : 0;
  if (res[0]!=0) res[0][141]=a141;
  a142=arg[0]? arg[0][142] : 0;
  if (res[0]!=0) res[0][142]=a142;
  a143=arg[0]? arg[0][143] : 0;
  if (res[0]!=0) res[0][143]=a143;
  a144=arg[0]? arg[0][144] : 0;
  if (res[0]!=0) res[0][144]=a144;
  a145=arg[0]? arg[0][145] : 0;
  if (res[0]!=0) res[0][145]=a145;
  a146=arg[0]? arg[0][146] : 0;
  if (res[0]!=0) res[0][146]=a146;
  a147=arg[0]? arg[0][147] : 0;
  if (res[0]!=0) res[0][147]=a147;
  a148=arg[0]? arg[0][148] : 0;
  if (res[0]!=0) res[0][148]=a148;
  a149=arg[0]? arg[0][149] : 0;
  if (res[0]!=0) res[0][149]=a149;
  a150=arg[0]? arg[0][150] : 0;
  if (res[0]!=0) res[0][150]=a150;
  a151=arg[0]? arg[0][151] : 0;
  if (res[0]!=0) res[0][151]=a151;
  a152=arg[0]? arg[0][152] : 0;
  if (res[0]!=0) res[0][152]=a152;
  a153=arg[0]? arg[0][153] : 0;
  if (res[0]!=0) res[0][153]=a153;
  a154=arg[0]? arg[0][154] : 0;
  if (res[0]!=0) res[0][154]=a154;
  a155=arg[0]? arg[0][155] : 0;
  if (res[0]!=0) res[0][155]=a155;
  a156=arg[0]? arg[0][156] : 0;
  if (res[0]!=0) res[0][156]=a156;
  a157=arg[0]? arg[0][157] : 0;
  if (res[0]!=0) res[0][157]=a157;
  a158=arg[0]? arg[0][158] : 0;
  if (res[0]!=0) res[0][158]=a158;
  a159=arg[0]? arg[0][159] : 0;
  if (res[0]!=0) res[0][159]=a159;
  a160=arg[0]? arg[0][160] : 0;
  if (res[0]!=0) res[0][160]=a160;
  a161=arg[0]? arg[0][161] : 0;
  if (res[0]!=0) res[0][161]=a161;
  a162=arg[0]? arg[0][162] : 0;
  if (res[0]!=0) res[0][162]=a162;
  a163=arg[0]? arg[0][163] : 0;
  if (res[0]!=0) res[0][163]=a163;
  a164=arg[0]? arg[0][164] : 0;
  if (res[0]!=0) res[0][164]=a164;
  a165=arg[0]? arg[0][165] : 0;
  if (res[0]!=0) res[0][165]=a165;
  a166=arg[0]? arg[0][166] : 0;
  if (res[0]!=0) res[0][166]=a166;
  a167=arg[0]? arg[0][167] : 0;
  if (res[0]!=0) res[0][167]=a167;
  a168=arg[0]? arg[0][168] : 0;
  if (res[0]!=0) res[0][168]=a168;
  a169=arg[0]? arg[0][169] : 0;
  if (res[0]!=0) res[0][169]=a169;
  a170=arg[0]? arg[0][170] : 0;
  if (res[0]!=0) res[0][170]=a170;
  a171=arg[0]? arg[0][171] : 0;
  if (res[0]!=0) res[0][171]=a171;
  a172=arg[0]? arg[0][172] : 0;
  if (res[0]!=0) res[0][172]=a172;
  a173=arg[0]? arg[0][173] : 0;
  if (res[0]!=0) res[0][173]=a173;
  a174=arg[0]? arg[0][174] : 0;
  if (res[0]!=0) res[0][174]=a174;
  a175=arg[0]? arg[0][175] : 0;
  if (res[0]!=0) res[0][175]=a175;
  a176=arg[0]? arg[0][176] : 0;
  if (res[0]!=0) res[0][176]=a176;
  a177=arg[0]? arg[0][177] : 0;
  if (res[0]!=0) res[0][177]=a177;
  a178=arg[0]? arg[0][178] : 0;
  if (res[0]!=0) res[0][178]=a178;
  a179=arg[0]? arg[0][179] : 0;
  if (res[0]!=0) res[0][179]=a179;
  a180=arg[0]? arg[0][180] : 0;
  if (res[0]!=0) res[0][180]=a180;
  a181=arg[0]? arg[0][181] : 0;
  if (res[0]!=0) res[0][181]=a181;
  a182=arg[0]? arg[0][182] : 0;
  if (res[0]!=0) res[0][182]=a182;
  a183=arg[0]? arg[0][183] : 0;
  if (res[0]!=0) res[0][183]=a183;
  a184=arg[0]? arg[0][184] : 0;
  if (res[0]!=0) res[0][184]=a184;
  a185=arg[0]? arg[0][185] : 0;
  if (res[0]!=0) res[0][185]=a185;
  a186=arg[0]? arg[0][186] : 0;
  if (res[0]!=0) res[0][186]=a186;
  a187=arg[0]? arg[0][187] : 0;
  if (res[0]!=0) res[0][187]=a187;
  a188=arg[0]? arg[0][188] : 0;
  if (res[0]!=0) res[0][188]=a188;
  a189=arg[0]? arg[0][189] : 0;
  if (res[0]!=0) res[0][189]=a189;
  a190=arg[0]? arg[0][190] : 0;
  if (res[0]!=0) res[0][190]=a190;
  a191=arg[0]? arg[0][191] : 0;
  if (res[0]!=0) res[0][191]=a191;
  a192=arg[0]? arg[0][192] : 0;
  if (res[0]!=0) res[0][192]=a192;
  a193=arg[0]? arg[0][193] : 0;
  if (res[0]!=0) res[0][193]=a193;
  a194=arg[0]? arg[0][194] : 0;
  if (res[0]!=0) res[0][194]=a194;
  a195=arg[0]? arg[0][195] : 0;
  if (res[0]!=0) res[0][195]=a195;
  a150=(a150+a150);
  if (res[0]!=0) res[0][196]=a150;
  a164=(a164+a151);
  if (res[0]!=0) res[0][197]=a164;
  a178=(a178+a152);
  if (res[0]!=0) res[0][198]=a178;
  a192=(a192+a153);
  if (res[0]!=0) res[0][199]=a192;
  a140=(a140+a010);
  if (res[0]!=0) res[0][200]=a140;
  a141=(a141+a024);
  if (res[0]!=0) res[0][201]=a141;
  a142=(a142+a038);
  if (res[0]!=0) res[0][202]=a142;
  a143=(a143+a052);
  if (res[0]!=0) res[0][203]=a143;
  a144=(a144+a066);
  if (res[0]!=0) res[0][204]=a144;
  a145=(a145+a080);
  if (res[0]!=0) res[0][205]=a145;
  a146=(a146+a094);
  if (res[0]!=0) res[0][206]=a146;
  a147=(a147+a108);
  if (res[0]!=0) res[0][207]=a147;
  a148=(a148+a122);
  if (res[0]!=0) res[0][208]=a148;
  a149=(a149+a136);
  if (res[0]!=0) res[0][209]=a149;
  a165=(a165+a165);
  if (res[0]!=0) res[0][210]=a165;
  a179=(a179+a166);
  if (res[0]!=0) res[0][211]=a179;
  a193=(a193+a167);
  if (res[0]!=0) res[0][212]=a193;
  a154=(a154+a011);
  if (res[0]!=0) res[0][213]=a154;
  a155=(a155+a025);
  if (res[0]!=0) res[0][214]=a155;
  a156=(a156+a039);
  if (res[0]!=0) res[0][215]=a156;
  a157=(a157+a053);
  if (res[0]!=0) res[0][216]=a157;
  a158=(a158+a067);
  if (res[0]!=0) res[0][217]=a158;
  a159=(a159+a081);
  if (res[0]!=0) res[0][218]=a159;
  a160=(a160+a095);
  if (res[0]!=0) res[0][219]=a160;
  a161=(a161+a109);
  if (res[0]!=0) res[0][220]=a161;
  a162=(a162+a123);
  if (res[0]!=0) res[0][221]=a162;
  a163=(a163+a137);
  if (res[0]!=0) res[0][222]=a163;
  a180=(a180+a180);
  if (res[0]!=0) res[0][223]=a180;
  a194=(a194+a181);
  if (res[0]!=0) res[0][224]=a194;
  a168=(a168+a012);
  if (res[0]!=0) res[0][225]=a168;
  a169=(a169+a026);
  if (res[0]!=0) res[0][226]=a169;
  a170=(a170+a040);
  if (res[0]!=0) res[0][227]=a170;
  a171=(a171+a054);
  if (res[0]!=0) res[0][228]=a171;
  a172=(a172+a068);
  if (res[0]!=0) res[0][229]=a172;
  a173=(a173+a082);
  if (res[0]!=0) res[0][230]=a173;
  a174=(a174+a096);
  if (res[0]!=0) res[0][231]=a174;
  a175=(a175+a110);
  if (res[0]!=0) res[0][232]=a175;
  a176=(a176+a124);
  if (res[0]!=0) res[0][233]=a176;
  a177=(a177+a138);
  if (res[0]!=0) res[0][234]=a177;
  a195=(a195+a195);
  if (res[0]!=0) res[0][235]=a195;
  a182=(a182+a013);
  if (res[0]!=0) res[0][236]=a182;
  a183=(a183+a027);
  if (res[0]!=0) res[0][237]=a183;
  a184=(a184+a041);
  if (res[0]!=0) res[0][238]=a184;
  a185=(a185+a055);
  if (res[0]!=0) res[0][239]=a185;
  a186=(a186+a069);
  if (res[0]!=0) res[0][240]=a186;
  a187=(a187+a083);
  if (res[0]!=0) res[0][241]=a187;
  a188=(a188+a097);
  if (res[0]!=0) res[0][242]=a188;
  a189=(a189+a111);
  if (res[0]!=0) res[0][243]=a189;
  a190=(a190+a125);
  if (res[0]!=0) res[0][244]=a190;
  a191=(a191+a139);
  if (res[0]!=0) res[0][245]=a191;
  a000=(a000+a000);
  if (res[0]!=0) res[0][246]=a000;
  a014=(a014+a001);
  if (res[0]!=0) res[0][247]=a014;
  a028=(a028+a002);
  if (res[0]!=0) res[0][248]=a028;
  a042=(a042+a003);
  if (res[0]!=0) res[0][249]=a042;
  a056=(a056+a004);
  if (res[0]!=0) res[0][250]=a056;
  a070=(a070+a005);
  if (res[0]!=0) res[0][251]=a070;
  a084=(a084+a006);
  if (res[0]!=0) res[0][252]=a084;
  a098=(a098+a007);
  if (res[0]!=0) res[0][253]=a098;
  a112=(a112+a008);
  if (res[0]!=0) res[0][254]=a112;
  a126=(a126+a009);
  if (res[0]!=0) res[0][255]=a126;
  a015=(a015+a015);
  if (res[0]!=0) res[0][256]=a015;
  a029=(a029+a016);
  if (res[0]!=0) res[0][257]=a029;
  a043=(a043+a017);
  if (res[0]!=0) res[0][258]=a043;
  a057=(a057+a018);
  if (res[0]!=0) res[0][259]=a057;
  a071=(a071+a019);
  if (res[0]!=0) res[0][260]=a071;
  a085=(a085+a020);
  if (res[0]!=0) res[0][261]=a085;
  a099=(a099+a021);
  if (res[0]!=0) res[0][262]=a099;
  a113=(a113+a022);
  if (res[0]!=0) res[0][263]=a113;
  a127=(a127+a023);
  if (res[0]!=0) res[0][264]=a127;
  a030=(a030+a030);
  if (res[0]!=0) res[0][265]=a030;
  a044=(a044+a031);
  if (res[0]!=0) res[0][266]=a044;
  a058=(a058+a032);
  if (res[0]!=0) res[0][267]=a058;
  a072=(a072+a033);
  if (res[0]!=0) res[0][268]=a072;
  a086=(a086+a034);
  if (res[0]!=0) res[0][269]=a086;
  a100=(a100+a035);
  if (res[0]!=0) res[0][270]=a100;
  a114=(a114+a036);
  if (res[0]!=0) res[0][271]=a114;
  a128=(a128+a037);
  if (res[0]!=0) res[0][272]=a128;
  a045=(a045+a045);
  if (res[0]!=0) res[0][273]=a045;
  a059=(a059+a046);
  if (res[0]!=0) res[0][274]=a059;
  a073=(a073+a047);
  if (res[0]!=0) res[0][275]=a073;
  a087=(a087+a048);
  if (res[0]!=0) res[0][276]=a087;
  a101=(a101+a049);
  if (res[0]!=0) res[0][277]=a101;
  a115=(a115+a050);
  if (res[0]!=0) res[0][278]=a115;
  a129=(a129+a051);
  if (res[0]!=0) res[0][279]=a129;
  a060=(a060+a060);
  if (res[0]!=0) res[0][280]=a060;
  a074=(a074+a061);
  if (res[0]!=0) res[0][281]=a074;
  a088=(a088+a062);
  if (res[0]!=0) res[0][282]=a088;
  a102=(a102+a063);
  if (res[0]!=0) res[0][283]=a102;
  a116=(a116+a064);
  if (res[0]!=0) res[0][284]=a116;
  a130=(a130+a065);
  if (res[0]!=0) res[0][285]=a130;
  a075=(a075+a075);
  if (res[0]!=0) res[0][286]=a075;
  a089=(a089+a076);
  if (res[0]!=0) res[0][287]=a089;
  a103=(a103+a077);
  if (res[0]!=0) res[0][288]=a103;
  a117=(a117+a078);
  if (res[0]!=0) res[0][289]=a117;
  a131=(a131+a079);
  if (res[0]!=0) res[0][290]=a131;
  a090=(a090+a090);
  if (res[0]!=0) res[0][291]=a090;
  a104=(a104+a091);
  if (res[0]!=0) res[0][292]=a104;
  a118=(a118+a092);
  if (res[0]!=0) res[0][293]=a118;
  a132=(a132+a093);
  if (res[0]!=0) res[0][294]=a132;
  a105=(a105+a105);
  if (res[0]!=0) res[0][295]=a105;
  a119=(a119+a106);
  if (res[0]!=0) res[0][296]=a119;
  a133=(a133+a107);
  if (res[0]!=0) res[0][297]=a133;
  a120=(a120+a120);
  if (res[0]!=0) res[0][298]=a120;
  a134=(a134+a121);
  if (res[0]!=0) res[0][299]=a134;
  a135=(a135+a135);
  if (res[0]!=0) res[0][300]=a135;
  if (res[0]!=0) res[0][301]=a150;
  if (res[0]!=0) res[0][302]=a164;
  if (res[0]!=0) res[0][303]=a178;
  if (res[0]!=0) res[0][304]=a192;
  if (res[0]!=0) res[0][305]=a140;
  if (res[0]!=0) res[0][306]=a141;
  if (res[0]!=0) res[0][307]=a142;
  if (res[0]!=0) res[0][308]=a143;
  if (res[0]!=0) res[0][309]=a144;
  if (res[0]!=0) res[0][310]=a145;
  if (res[0]!=0) res[0][311]=a146;
  if (res[0]!=0) res[0][312]=a147;
  if (res[0]!=0) res[0][313]=a148;
  if (res[0]!=0) res[0][314]=a149;
  if (res[0]!=0) res[0][315]=a165;
  if (res[0]!=0) res[0][316]=a179;
  if (res[0]!=0) res[0][317]=a193;
  if (res[0]!=0) res[0][318]=a154;
  if (res[0]!=0) res[0][319]=a155;
  if (res[0]!=0) res[0][320]=a156;
  if (res[0]!=0) res[0][321]=a157;
  if (res[0]!=0) res[0][322]=a158;
  if (res[0]!=0) res[0][323]=a159;
  if (res[0]!=0) res[0][324]=a160;
  if (res[0]!=0) res[0][325]=a161;
  if (res[0]!=0) res[0][326]=a162;
  if (res[0]!=0) res[0][327]=a163;
  if (res[0]!=0) res[0][328]=a180;
  if (res[0]!=0) res[0][329]=a194;
  if (res[0]!=0) res[0][330]=a168;
  if (res[0]!=0) res[0][331]=a169;
  if (res[0]!=0) res[0][332]=a170;
  if (res[0]!=0) res[0][333]=a171;
  if (res[0]!=0) res[0][334]=a172;
  if (res[0]!=0) res[0][335]=a173;
  if (res[0]!=0) res[0][336]=a174;
  if (res[0]!=0) res[0][337]=a175;
  if (res[0]!=0) res[0][338]=a176;
  if (res[0]!=0) res[0][339]=a177;
  if (res[0]!=0) res[0][340]=a195;
  if (res[0]!=0) res[0][341]=a182;
  if (res[0]!=0) res[0][342]=a183;
  if (res[0]!=0) res[0][343]=a184;
  if (res[0]!=0) res[0][344]=a185;
  if (res[0]!=0) res[0][345]=a186;
  if (res[0]!=0) res[0][346]=a187;
  if (res[0]!=0) res[0][347]=a188;
  if (res[0]!=0) res[0][348]=a189;
  if (res[0]!=0) res[0][349]=a190;
  if (res[0]!=0) res[0][350]=a191;
  if (res[0]!=0) res[0][351]=a000;
  if (res[0]!=0) res[0][352]=a014;
  if (res[0]!=0) res[0][353]=a028;
  if (res[0]!=0) res[0][354]=a042;
  if (res[0]!=0) res[0][355]=a056;
  if (res[0]!=0) res[0][356]=a070;
  if (res[0]!=0) res[0][357]=a084;
  if (res[0]!=0) res[0][358]=a098;
  if (res[0]!=0) res[0][359]=a112;
  if (res[0]!=0) res[0][360]=a126;
  if (res[0]!=0) res[0][361]=a015;
  if (res[0]!=0) res[0][362]=a029;
  if (res[0]!=0) res[0][363]=a043;
  if (res[0]!=0) res[0][364]=a057;
  if (res[0]!=0) res[0][365]=a071;
  if (res[0]!=0) res[0][366]=a085;
  if (res[0]!=0) res[0][367]=a099;
  if (res[0]!=0) res[0][368]=a113;
  if (res[0]!=0) res[0][369]=a127;
  if (res[0]!=0) res[0][370]=a030;
  if (res[0]!=0) res[0][371]=a044;
  if (res[0]!=0) res[0][372]=a058;
  if (res[0]!=0) res[0][373]=a072;
  if (res[0]!=0) res[0][374]=a086;
  if (res[0]!=0) res[0][375]=a100;
  if (res[0]!=0) res[0][376]=a114;
  if (res[0]!=0) res[0][377]=a128;
  if (res[0]!=0) res[0][378]=a045;
  if (res[0]!=0) res[0][379]=a059;
  if (res[0]!=0) res[0][380]=a073;
  if (res[0]!=0) res[0][381]=a087;
  if (res[0]!=0) res[0][382]=a101;
  if (res[0]!=0) res[0][383]=a115;
  if (res[0]!=0) res[0][384]=a129;
  if (res[0]!=0) res[0][385]=a060;
  if (res[0]!=0) res[0][386]=a074;
  if (res[0]!=0) res[0][387]=a088;
  if (res[0]!=0) res[0][388]=a102;
  if (res[0]!=0) res[0][389]=a116;
  if (res[0]!=0) res[0][390]=a130;
  if (res[0]!=0) res[0][391]=a075;
  if (res[0]!=0) res[0][392]=a089;
  if (res[0]!=0) res[0][393]=a103;
  if (res[0]!=0) res[0][394]=a117;
  if (res[0]!=0) res[0][395]=a131;
  if (res[0]!=0) res[0][396]=a090;
  if (res[0]!=0) res[0][397]=a104;
  if (res[0]!=0) res[0][398]=a118;
  if (res[0]!=0) res[0][399]=a132;
  if (res[0]!=0) res[0][400]=a105;
  if (res[0]!=0) res[0][401]=a119;
  if (res[0]!=0) res[0][402]=a133;
  if (res[0]!=0) res[0][403]=a120;
  if (res[0]!=0) res[0][404]=a134;
  if (res[0]!=0) res[0][405]=a135;
  if (res[0]!=0) res[0][406]=a000;
  if (res[0]!=0) res[0][407]=a014;
  if (res[0]!=0) res[0][408]=a028;
  if (res[0]!=0) res[0][409]=a042;
  if (res[0]!=0) res[0][410]=a056;
  if (res[0]!=0) res[0][411]=a070;
  if (res[0]!=0) res[0][412]=a084;
  if (res[0]!=0) res[0][413]=a098;
  if (res[0]!=0) res[0][414]=a112;
  if (res[0]!=0) res[0][415]=a126;
  if (res[0]!=0) res[0][416]=a015;
  if (res[0]!=0) res[0][417]=a029;
  if (res[0]!=0) res[0][418]=a043;
  if (res[0]!=0) res[0][419]=a057;
  if (res[0]!=0) res[0][420]=a071;
  if (res[0]!=0) res[0][421]=a085;
  if (res[0]!=0) res[0][422]=a099;
  if (res[0]!=0) res[0][423]=a113;
  if (res[0]!=0) res[0][424]=a127;
  if (res[0]!=0) res[0][425]=a030;
  if (res[0]!=0) res[0][426]=a044;
  if (res[0]!=0) res[0][427]=a058;
  if (res[0]!=0) res[0][428]=a072;
  if (res[0]!=0) res[0][429]=a086;
  if (res[0]!=0) res[0][430]=a100;
  if (res[0]!=0) res[0][431]=a114;
  if (res[0]!=0) res[0][432]=a128;
  if (res[0]!=0) res[0][433]=a045;
  if (res[0]!=0) res[0][434]=a059;
  if (res[0]!=0) res[0][435]=a073;
  if (res[0]!=0) res[0][436]=a087;
  if (res[0]!=0) res[0][437]=a101;
  if (res[0]!=0) res[0][438]=a115;
  if (res[0]!=0) res[0][439]=a129;
  if (res[0]!=0) res[0][440]=a060;
  if (res[0]!=0) res[0][441]=a074;
  if (res[0]!=0) res[0][442]=a088;
  if (res[0]!=0) res[0][443]=a102;
  if (res[0]!=0) res[0][444]=a116;
  if (res[0]!=0) res[0][445]=a130;
  if (res[0]!=0) res[0][446]=a075;
  if (res[0]!=0) res[0][447]=a089;
  if (res[0]!=0) res[0][448]=a103;
  if (res[0]!=0) res[0][449]=a117;
  if (res[0]!=0) res[0][450]=a131;
  if (res[0]!=0) res[0][451]=a090;
  if (res[0]!=0) res[0][452]=a104;
  if (res[0]!=0) res[0][453]=a118;
  if (res[0]!=0) res[0][454]=a132;
  if (res[0]!=0) res[0][455]=a105;
  if (res[0]!=0) res[0][456]=a119;
  if (res[0]!=0) res[0][457]=a133;
  if (res[0]!=0) res[0][458]=a120;
  if (res[0]!=0) res[0][459]=a134;
  if (res[0]!=0) res[0][460]=a135;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_p_global_precompute_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_problem_p_global_precompute_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_p_global_precompute_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_p_global_precompute_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_problem_p_global_precompute_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_problem_p_global_precompute_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_p_global_precompute_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_problem_p_global_precompute_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_p_global_precompute_fun_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int ocp_problem_p_global_precompute_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ocp_problem_p_global_precompute_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_p_global_precompute_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_problem_p_global_precompute_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_p_global_precompute_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_problem_p_global_precompute_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_problem_p_global_precompute_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_problem_p_global_precompute_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
